### ISSUE TITLE
Can't add speakers details without website and twitter fields filled up.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2221] opened 2019-02-22 16:58 UTC
**Describe the bug**

User can't add the speaker details without filling up website and twitter link even when it is optional field.
**To Reproduce**
1. Make twitter and website field optional.
2. Try submitting speaker details without filling up website and twitter field.
3. Click save.
4. See the error.

**Expected behavior**

User should be allowed to submit speaker details when website and twitter link is optional.
**Screenshots**

![ezgif-1-1c5abef18a4f](https://user-images.githubusercontent.com/21174572/53257842-2490d300-36f1-11e9-89b6-b1433f0a71ac.gif)

**Additional context**

I would like to work on it.

**Comment by uds5501** [comment] 2019-03-01 07:56
@Anupam-dagar If you have not invested much time in it, shall I give it a try?

**Comment by Anupam-dagar** [comment] 2019-03-01 08:03
Sure

**Comment by uds5501** [comment] 2019-03-01 08:59
@Anupam-dagar I followed the GIF by a new user and the event creator and yet I cannot recreate this issue. Could you please point out anything important which should be kept in mind while recreating it?

**Comment by Anupam-dagar** [comment] 2019-03-01 16:27
@uds5501 I used the default settings but the steps were done using admin user.

**Comment by uds5501** [comment] 2019-03-01 16:58
@Anupam-dagar Sorry but can't recreate this issue that way either. Try updating your server and see if it still persists

**Comment by uds5501** [comment] 2019-04-14 09:46
@CosmicCoder96 This is working fine, kindly verify and close if can't reproduce

**Comment by Anupam-dagar** [comment] 2019-04-14 16:14
@uds5501 I guess this issue was at my machine only at that time probably because of messed up migrations. This issue is good to be closed.
CC: @CosmicCoder96

**Comment by kushthedude** [comment] 2019-04-27 01:36
@Anupam-dagar You can close the issue 😄

**Closed** 2019-04-28 11:50 UTC
