### ISSUE TITLE
Redirect page after the login/signup on Call for speakers

### ISSUE THREAD

**Issue by thanostx** [fossasia/open-event-frontend#2396] opened 2019-03-26 15:52 UTC
**Edit** - See #2370 for relevant discussion
- @iamareebjamal 

**Describe the bug**

When an unauthenticated/unregistered user login/register to submit a session, he/she gets redirected to the homepage instead of the event that he/she was.

**To Reproduce**
1. Go to 'An event with open Call for Speakers section'
2. Click on 'Submit Proposal'
3. Login or Signup using an account
4. After this action the page redirects to homepage

**Expected behavior**

The page should redirect to the view of the "Call for speakers" section on the specified event.

**Desktop & Smartphones (please complete the following information):**
 - OS: Any OS
 - Browser: Any browser

**Comment by uds5501** [comment] 2019-03-27 02:54
@thanostx looking into it

**Comment by kushthedude** [comment] 2019-03-27 04:40
@uds5501 i was lookin into it and when we click on login/signup it directly lands us to the login default page and it dont have any memory from which login was called.

**Comment by prateekj117** [comment] 2019-04-20 15:07
@uds5501 Working on it?

**Comment by uds5501** [comment] 2019-04-20 15:08
@prateekj117 a PR is already opened  in #2370

**Comment by kushthedude** [comment] 2019-05-29 19:38
@CosmicCoder96 Its duplicate of #2370 ,

**Comment by kushthedude** [comment] 2019-11-30 12:22
Duplicate of #3673

**Comment by iamareebjamal** [comment] 2019-12-01 10:07
This should have been closed in favor of #2370 as it has most conversation regarding the bug and was opened before. But since this has the most issues marked as duplicate, letting it be the parent issue

**Comment by iamareebjamal** [comment] 2019-12-01 10:12
@kushthedude See PR https://github.com/fossasia/open-event-frontend/pull/2377 and create a corresponding fix along the lines

**Comment by kushthedude** [comment] 2019-12-01 10:26
I wont be able to work on this until next week, Anyone can take this up if
they find a fix for the following.

**Closed** 2020-01-18 09:43 UTC
Labels: Priority: High, Priority: Urgent, bug
