### ISSUE TITLE
Group: Upcoming events are not loading

### ISSUE THREAD

**Issue by MeghalBisht** [fossasia/open-event-frontend#7687] opened 2021-08-11 18:41 UTC
Having upcoming events associated with my account, yet they dont appear in group edit form.
![Screenshot from 2021-08-12 00-12-06](https://user-images.githubusercontent.com/61330148/129085142-74d18983-cabb-4a03-9fac-b19ffb7fef2e.png)
![Screenshot from 2021-08-12 00-11-59](https://user-images.githubusercontent.com/61330148/129085156-1156c2cc-c266-48f4-bf91-0b6cb28a2f0e.png)

**Comment by ranjitkshah** [comment] 2021-08-11 19:06
@MeghalBisht  I also faced it and explored it. it is due to pagination of event api. If In first fetch of  event there is no upcoming event then it wil show no upcoming events on first time, if we scroll and load  more events then it will show upcoming events if any upcoming events is present. we have to think other logic for fetching upcomings or past events

cc: @maze-runnar @sachinchauhan2889

**Comment by maze-runnar** [comment] 2021-08-12 02:56
@ranjitkshah if the issue is due to what you are saying, try reducing `triggerOffset` from 1000 to 300. Because I am not able reprodce.

**Comment by mariobehling** [comment] 2021-09-19 18:20
Seems to be working in my tests. Therefore closing it for now. Need to keep testing though in case it just appears in some circumstances.

**Closed by mariobehling** 2021-09-19 18:20 UTC
Labels: bug
