### ISSUE TITLE
Event hash-tags coming out of the containing box

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-frontend#4573] opened 2020-07-17 10:59 UTC
**Describe the bug**

Event hash-tags are not coming properly inside the containing box

**To Reproduce**
Steps to reproduce the behaviour:
1. First create event of type `#HobbiesSpecialInterest`, `#CampTreatRetreat` and `#AnimeComics` 
2. Go to home page
3. Scroll down to the event created in step 1

**Expected behaviour**

Hash tags should properly come inside the containing box

**Screenshots**

![event-hashtags](https://user-images.githubusercontent.com/43299408/87779532-8d2ea180-c84a-11ea-8eeb-3c6787d19a63.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Browser: Firefox
 - Version: 78.0.2

**Additional context**

Will work on this

**Comment by iamareebjamal** [comment] 2020-07-31 14:50
Duplicate of #2346

**Closed by iamareebjamal** 2020-07-31 14:50 UTC
Labels: bug, ui
