### ISSUE TITLE
Pressing Pay Now button leads to a standstill

### ISSUE THREAD

**Issue by unnawut** [fossasia/open-event-frontend#3337] opened 2019-07-31 13:51 UTC
**Describe the bug**
Pressing "Pay Now" on the order summary page does not cause any change on the page.

**To Reproduce**
1. Go to https://eventyay.com/e/aac5bcc7
2. Pick one Early Bird ticket
3. Press "Pay Now"
4. Fill in the billing form
5. Chose "credit card" as payment method
6. Click "Proceed to checkout"
7. Click "Pay Now"

At this point after clicking, nothing happens. Error stacktrace appears on the console (as pasted down below).

![image](https://user-images.githubusercontent.com/921194/62216795-a5a47280-b3d3-11e9-8526-3128bda675ca.png)

**Expected behavior**
Either:
1. The site should proceed to letting me fill in my credit card information to pay.
2. Display error that it could not proceed to payment.
3. If this is a misconfiguration error, the "Pay Now" button should be disabled or hidden since the landing page if the payment information is not configured properly, as the impact on user experience is much higher after the user has already filled in the billing information.

**Stacktrace**
```
vendor-48d1cff85f863d1337bccb28f2fa97e7.js:10784 Uncaught Error: [ember-cli-stripe] Missing required `key` param
    at n._stripeHandler (vendor-48d1cff85f863d1337bccb28f2fa97e7.js:10784)
    at vendor-48d1cff85f863d1337bccb28f2fa97e7.js:10779
    at y (vendor-48d1cff85f863d1337bccb28f2fa97e7.js:5237)
    at S (vendor-48d1cff85f863d1337bccb28f2fa97e7.js:5247)
    at vendor-48d1cff85f863d1337bccb28f2fa97e7.js:5255
    at t.invoke (vendor-48d1cff85f863d1337bccb28f2fa97e7.js:4776)
    at e.t.flush (vendor-48d1cff85f863d1337bccb28f2fa97e7.js:4768)
    at e.t.flush (vendor-48d1cff85f863d1337bccb28f2fa97e7.js:4781)
    at e.n._end (vendor-48d1cff85f863d1337bccb28f2fa97e7.js:4843)
    at e.n.end (vendor-48d1cff85f863d1337bccb28f2fa97e7.js:4798)
```

**Additional details (please complete the following information):**
 - OS: MacOS 10.14.6 (18G84)
 - Browser: Chrome 75.0.3770.142 (Official Build) (64-bit)

**Comment by iamareebjamal** [comment] 2019-07-31 13:57
Duplicate of #3310

**Closed by iamareebjamal** 2019-07-31 13:57 UTC
