### ISSUE TITLE
Pagination for Admin sales

### ISSUE THREAD

**Issue by YogeshSharma0201** [fossasia/open-event-frontend#2141] opened 2019-02-07 08:06 UTC
**Is your feature request related to a problem? Please describe.**
Presently Pagination is not implemented for Admin Sales section.

**Describe the solution you'd like**
Implement Pagination similar to other admin sections.

I'm working on it.

**Comment by CosmicCoder96** [comment] 2019-05-28 08:31
duplicate of https://github.com/fossasia/open-event-frontend/issues/2794

**Closed by CosmicCoder96** 2019-05-28 08:31 UTC
Labels: bug
