### ISSUE TITLE
Event Dashboard: Revision Info seems hardcoded

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1923] opened 2019-01-21 08:54 UTC
The revision information on the dashboard always shows 6 revisions no matter if more revisions are made. Please show the actual revision information.

![screenshot from 2019-01-21 09-50-06](https://user-images.githubusercontent.com/1583873/51463056-895bb500-1d62-11e9-822c-3370d5145ec2.png)

**Comment by amanjain25** [comment] 2019-01-21 17:00
I would like to work on this issue

**Comment by amanjain25** [comment] 2019-01-22 14:24
@mariobehling could you please tell what does this revision mean here? Is it the number of times event has been edited or something else?

**Comment by mariobehling** [comment] 2019-01-23 15:23
Yes.

**Comment by uds5501** [comment] 2019-01-25 22:54
@amanjain25 if you are not working on it, can I have a look?

**Comment by uds5501** [comment] 2019-01-28 13:03
@mariobehling The deployed version of eventyay does not have this error. Kindly close this issue.
![image](https://user-images.githubusercontent.com/21087061/51838027-2900e080-232b-11e9-96fd-08d571e64c7e.png)

**Comment by shreyanshdwivedi** [comment] 2019-02-01 18:33
The revision info is indeed hardcoded. I can reproduce this issue locally. But is revision info supported by server? If not, I would like to take up this issue.

**Comment by shreyanshdwivedi** [comment] 2019-03-19 17:20
@CosmicCoder96 I think, for now we should comment out `No. of revisions` till we get backend ready to implement it. Your thoughts?

**Comment by kushthedude** [comment] 2019-08-25 17:19
Duplicate of #2191

**Closed** 2019-08-25 17:20 UTC
Labels: feature
