### ISSUE TITLE
Account Profile Image no longer visible

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6833] opened 2021-02-25 23:17 UTC
Profile image no longer visible on account page for admin even though it is still visible on event pages that use the same image.

I remember this problem existed in the middle of last year for some time too and I think it was a permissions issue.

The issue happens for about 5 days.

![Screenshot from 2021-02-26 00-14-31](https://user-images.githubusercontent.com/1583873/109232068-ef2f8c00-77c7-11eb-940c-bc267719a39d.png)

**Comment by anjali1102** [comment] 2021-02-27 16:48
Taking up this issue

**Comment by ankitashaw514** [comment] 2021-03-03 15:50
Can i work on this?

**Comment by iamareebjamal** [comment] 2021-03-03 23:14
Duplicate of #6902

**Closed by iamareebjamal** 2021-03-03 23:14 UTC
Labels: bug, codeheat
