### ISSUE TITLE
Pagination missing from Admin Sales Tab

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2676] opened 2019-04-16 07:54 UTC
The admin sales tab does not have pagination (https://next.eventyay.com/admin/sales). Expected: When there are a lot of events the different sub menu tabs should be paginated. It would not be possible to load thousand of events.

**Comment by kushthedude** [comment] 2019-04-16 08:06
I think some one is already on it #2167

**Comment by CosmicCoder96** [comment] 2019-05-28 08:24
duplicate of https://github.com/fossasia/open-event-frontend/issues/2794

**Closed by CosmicCoder96** 2019-05-28 08:24 UTC
Labels: bug
