### ISSUE TITLE
Ordering ticket with taxes throws Unhandled Promise Rejection

### ISSUE THREAD

**Issue by uds5501** [fossasia/open-event-frontend#3074] opened 2019-06-05 19:15 UTC
**Describe the bug**

Tax information not being saved in edit event steps

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an event
2. Save it without tax
3. Edit it and add tax information

**Expected behaviour**

Tax information should be saved

**Screenshots**

![Screenshot from 2019-06-06 00-40-48](https://user-images.githubusercontent.com/21087061/58983189-df059b00-87f3-11e9-87f3-a6068423cb08.png)

**Stack trace**
![Screenshot from 2019-06-06 00-44-41](https://user-images.githubusercontent.com/21087061/58983430-681cd200-87f4-11e9-8fef-e3ed11ac2aaa.png)

**Additional context**

Up for grabs

**Comment by kushthedude** [comment] 2019-06-05 23:55
@uds5501 I am not able to get the following error ?

**Comment by kushthedude** [comment] 2019-06-05 23:59
<img width="1440" alt="Screenshot 2019-06-06 at 5 29 27 AM" src="https://user-images.githubusercontent.com/44091822/58997872-1425e380-881c-11e9-94e8-5956ae806353.png">

**Comment by uds5501** [comment] 2019-06-06 05:28
@kushthedude Try making an event without tax. Then add tax in edit event. Tell me what you see

**Comment by kushthedude** [comment] 2019-06-06 05:34
@uds5501 
<img width="1440" alt="Screenshot 2019-06-06 at 11 02 53 AM" src="https://user-images.githubusercontent.com/44091822/59009302-a7760d80-884a-11e9-8b45-40c803072f3a.png">
 I was able to do it successfully
Rather I am getting this error when I try to buy tickets of that event -:

<img width="1296" alt="Screenshot 2019-06-06 at 11 03 30 AM" src="https://user-images.githubusercontent.com/44091822/59009334-c7a5cc80-884a-11e9-8fa1-cbbc8a13a833.png">

**Comment by kushthedude** [comment] 2019-06-06 05:34
@shreyanshdwivedi Can you please check on your local too ?

**Comment by shreyanshdwivedi** [comment] 2019-06-06 06:07
@uds5501 @kushthedude I'm unable to reproduce it on my local. Both the frontend and server are synced.

**Comment by uds5501** [comment] 2019-06-06 06:08
@kushthedude @shreyanshdwivedi should I attach a gif?

**Comment by kushthedude** [comment] 2019-06-06 06:09
@uds5501 My both repo are already in sync with development

**Comment by kushthedude** [comment] 2019-06-06 06:10
@shreyanshdwivedi can you check the following please ?
> @uds5501
> 
> I was able to do it successfully
> Rather I am getting this error when I try to buy tickets of that event -:
> 
> <img alt="Screenshot 2019-06-06 at 11 03 30 AM" width="1296" src="https://user-images.githubusercontent.com/44091822/59009334-c7a5cc80-884a-11e9-8fa1-cbbc8a13a833.png">

**Comment by uds5501** [comment] 2019-06-06 06:11
@kushthedude okay weird, I can't reproduce this now locally either.

**Comment by kushthedude** [comment] 2019-06-06 06:11
@uds5501 Can you check the above i stated ?

**Comment by shreyanshdwivedi** [comment] 2019-06-06 06:12
@kushthedude yes I'm getting similar `Unhandled promise error`

**Comment by kushthedude** [comment] 2019-06-06 06:13
@uds5501 Can you change the PR title and Screenshot if you can also reproduce the following ?

**Comment by uds5501** [comment] 2019-06-06 06:13
@kushthedude @shreyanshdwivedi order placed successfully:

![image](https://user-images.githubusercontent.com/21087061/59010837-42251b00-8850-11e9-8538-191a4e7fb0d5.png)

**Comment by kushthedude** [comment] 2019-06-06 06:13
> @kushthedude @shreyanshdwivedi order placed successfully:
> 
> ![image](https://user-images.githubusercontent.com/21087061/59010837-42251b00-8850-11e9-8538-191a4e7fb0d5.png)

Where is tax in it ?

**Comment by uds5501** [comment] 2019-06-06 06:15
@kushthedude weird, the tax ain't getting saved. again
![image](https://user-images.githubusercontent.com/21087061/59010895-84e6f300-8850-11e9-9f83-a822d5e14ec1.png)

**Comment by kushthedude** [comment] 2019-06-06 06:17
@uds5501 Can you please clear the cache of browser once and try again ?

**Comment by uds5501** [comment] 2019-06-06 06:17
@kushthedude cool, trying.

**Comment by uds5501** [comment] 2019-06-06 06:20
@kushthedude No errors faced even with a tax:

![image](https://user-images.githubusercontent.com/21087061/59011127-3ede5f00-8851-11e9-9242-2d706732ade8.png)

**Comment by kushthedude** [comment] 2019-06-06 06:21
@uds5501 Was the even newly created ?

**Comment by uds5501** [comment] 2019-06-06 06:22
@kushthedude Yes.

**Comment by kushthedude** [comment] 2019-06-06 06:22
Weird @shreyanshdwivedi You are able to reproduce the `Unhandled Promise Rejection` , Right ?

**Comment by shreyanshdwivedi** [comment] 2019-06-06 06:29
Yes @kushthedude

**Comment by kushthedude** [comment] 2019-06-06 06:30
@uds5501 It would be great if you could change `PR Title`

**Comment by kushthedude** [comment] 2019-07-12 03:34
Closing, for now, Not being able to face it for quite a few days. 
If anyone still faces the issue, Please report and reopen, Thanks.

**Closed by kushthedude** 2019-07-12 03:34 UTC
Labels: bug, discussion
