### ISSUE TITLE
Login success should redirect to the last page user wanted to access.

### ISSUE THREAD

**Issue by prateekj117** [fossasia/open-event-frontend#2470] opened 2019-04-03 16:51 UTC
**Describe the bug**
Say a logged out user click on create event, user is redirected to login page, which on success redirects to home page.

**Expected behavior**
Login success should redirect to the last page user wanted to access.

**Additional context**
Working on it.

**Comment by kushthedude** [comment] 2019-04-03 23:46
Don't you think its similar to #2396  , But a more general implementation !

**Comment by CosmicCoder96** [comment] 2019-04-04 07:30
Duplicate of #2396 - will be fixed when it is solved.

**Closed by CosmicCoder96** 2019-04-04 07:30 UTC
