### ISSUE TITLE
Adding search bar with event name, location & date (UI only)

### ISSUE THREAD

**Issue by harshitagupta30** [fossasia/open-event-frontend#78] opened 2017-05-24 08:48 UTC
** I am submitting a **
 - [x] feature request

**ScreenShot**
![selection_047](https://cloud.githubusercontent.com/assets/12701036/26394173/ac7e6e18-4089-11e7-8832-3fc61017d683.png)

- Located at "/"
- The button "search" need not be actionable
-  Reference for button: https://semantic-ui.com/elements/button.html
for dropdown: https://semantic-ui.com/modules/dropdown.html

I want to work on this. Also, @niranjan94 can we divert this to "/explore" ?

**Comment by niranjan94** [comment] 2017-05-24 08:49
Duplicate of #9

**Closed by niranjan94** 2017-05-24 08:49 UTC
