### ISSUE TITLE
Virtual Events: Jitsi Rooms not visible

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6262] opened 2021-01-07 01:51 UTC
Jitis rooms regularly are not available in virtual events. Testing the source URL the rooms are there, but they do not show up on the platform. Then another time they do show up. Maybe caching issue?

![Screenshot from 2021-01-07 02-49-58](https://user-images.githubusercontent.com/1583873/103841137-35535380-5093-11eb-835e-2d9b157c1764.png)

![Screenshot from 2021-01-07 02-51-35](https://user-images.githubusercontent.com/1583873/103841179-4603c980-5093-11eb-9e59-bbf597b9d667.png)

**Comment by iamareebjamal** [comment] 2021-01-07 05:36
Link to the room? Duplicate of #6209?

There is no error in the console which shows up any reason for failure. Did you try reloading? Does it work on reload or stays that way?

**Closed** 2021-01-07 10:08 UTC
Labels: duplicate
