### ISSUE TITLE
Appropriate error message is showing only on first click on ordering a free ticket from an unverified account.

### ISSUE THREAD

**Issue by msk4862** [fossasia/open-event-frontend#3379] opened 2019-08-11 16:39 UTC
**Describe the bug**
Appropriate error messege is showing only first time on ordering a free ticket from an unverified account.
If we click on the "order now" button again then its showing an unappropriate error message.

**To Reproduce**
Steps to reproduce the behaviour:
1. Login from an unverified account
2. Click on an event
3. Click on order now button for free ticket then an appropriate message will appear :- ("Unverified user cannot place free orders")
4. But then if you click again on order now button then it shows an unappropriate error message :-
(**Error: Ember Data Request PATCH https://api.eventyay.com/v1/attendees/10769 returned a 422 Payload (application/vnd.api+json) [object Object]**)

**Expected behaviour**
It should show "Unverified user cannot place free orders" each time

**Screenshots**
![bug](https://user-images.githubusercontent.com/24875366/62835915-4d932900-bc7b-11e9-89bd-9912cf327262.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 76.0.3

**Comment by kushthedude** [comment] 2019-08-11 17:30
Duplicate of #3278

**Closed by kushthedude** 2019-08-11 17:30 UTC
