### ISSUE TITLE
Adding Default Image Incase Any Event Logo is not selected.

### ISSUE THREAD

**Issue by sk9331657** [fossasia/open-event-frontend#1881] opened 2019-01-17 19:16 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Working on this.

**Comment by mariobehling** [comment] 2019-01-17 23:11
As we progress, please help and stick more closely to best practices, e.g. add sufficient info and screenshot to your issues and PRs. Thank you!

**Comment by CosmicCoder96** [comment] 2019-01-21 18:13
Duplicate of https://github.com/fossasia/open-event-frontend/issues/1853

**Closed by CosmicCoder96** 2019-01-21 18:13 UTC
