### ISSUE TITLE
Enhance UI for TicketFlow

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#2442] opened 2019-04-01 02:38 UTC
**Describe the bug**

As Ticket-Flow was implemented as Eventyay V.1 , Phase - 1 and Phase - 2 are completed according to #1994 but there are many bugs created due to it .
Some are enlisted below :-
1.) When a unregistered user orders tickets or create an order, A random password is generated after this and the credentials of that users are stored in database as done in #2003,
This should be avoided as if that user wants to register for the Site , He needs to get his old password .
2.) As done in #2028  When a user enters the Email of registered user , The email is fixed to the box and the user cant edit the email after this .
3.) As stated in point 2 , The email of the user cant set empty until a refresh has been called.
4.) "You have previously registered with this email address" dialogue box generated in step 2 is encoded as a button rather than a simple message .

**Expected behavior**

Fix All such bugs and more if found .

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser: Chrome
 - Version: 73.0

**Additional context**

I would like to fix the complete ticket flow route .

**Comment by kushthedude** [comment] 2019-04-01 02:39
@CosmicCoder96 @ritikamotwani Your reviews on it ?

**Comment by CosmicCoder96** [comment] 2019-04-01 02:47
> When a unregistered user orders tickets or create an order, A random password is generated after this and the credentials of that users are stored in database as done in #2003,
This should be avoided as if that user wants to register for the Site , He needs to get his old password .

The user is also mailed a link to reset his password simultaneously. So he can always use it to sign in later. It seems you haven't set up test mail server correctly.

You can make the UI enhancements. Logic shouldn't change.=

**Comment by kushthedude** [comment] 2019-04-01 02:50
@CosmicCoder96 Dont you think a guest session type of thing would be more beneficial ,
If user only want tickets for some concert or some seminar he can simply checkout with details providing his email and phone number.😅

**Comment by CosmicCoder96** [comment] 2019-04-01 02:56
umm @kushthedude isn't that what he is exactly doing now? 
He provides an email, contact info and checks out.

**Comment by CosmicCoder96** [comment] 2019-04-01 02:57
We send him the tickets and a separate mail for logging in later if he wants to. We don't enforce setting up a password if he just wants to buy a ticket.

**Comment by kushthedude** [comment] 2019-04-01 02:58
@CosmicCoder96 Just assume user comes to just buy tickets again and then rather than just checking out he will see the dialogue box which was implemented in phase-2 .

**Comment by CosmicCoder96** [comment] 2019-04-01 03:02
@kushthedude we have other plans for that later, during gsoc. We will make it similar to eventbrite, currently orders api requires JWT authentication -- not an option to do it like that. The orders api requires refactoring.

**Comment by iamareebjamal** [comment] 2020-07-18 10:32
The details of the issue are mention in #4543 and fixed in #4569 

Guest mode buying will disallow the user to manage its tickets later on, so for now, this is the way to go

**Comment by edenyay** [comment] 2020-07-26 07:11
Hi @iamareebjamal, I think there is something we need to enhance in the ticket flow after switching from pdf attachments to link in the confirmation email. 

2 issues I have encountered today: 

1. When click on the link on confirmation email to view ticket/order, ticket buyer will be directed to eventyay login page (if they are not logged in eventyay). After they login, nothing appears. They then need to go **My Tickets** tab manually to view the order. 

2. I logged in to evenyay with one account (1), and I am able to view the ticket purchased by another account (2) by clicking on the the generated confirmation link sent to that second account. Not sure if this is an issue, though.

**Comment by iamareebjamal** [comment] 2020-07-26 07:21
Can you please paste the link in which nothing was appearing? I tested that it was redirecting to order overview page.

For 2nd issue as well I'd need a link, you shouldn't be able to see the order info of another user unless you're an organizer or admin

**Comment by edenyay** [comment] 2020-07-26 08:18
> Can you please paste the link in which nothing was appearing? I tested that it was redirecting to order overview page.

Here is the confirmation link https://eventyay.com/orders/4d47182c-a793-45ac-b0f6-df3386823f7d/view sent to my email. And here is the [screencast](https://youtu.be/TbXrBq5jIK4) of the issue.

> For 2nd issue as well I'd need a link, you shouldn't be able to see the order info of another user unless you're an organizer or admin

Oh i got it. have checked it again. You are right, because i was logged in as an organizer so I was able to see the ticket purchased by that attendee.

**Comment by iamareebjamal** [comment] 2020-07-26 08:43
I have reproduced the first issue. Will fix it, thanks

**Comment by mariobehling** [comment] 2020-09-03 13:26
We have diverted from the original issue description and the ticket code has been re-implemented in some ways. For any problems please refile in a dedicated issue.

**Closed by mariobehling** 2020-09-03 13:26 UTC
Labels: needs-review
