### ISSUE TITLE
Organizer unable to add new speakers into new sessions 

### ISSUE THREAD

**Issue by edenyay** [fossasia/open-event-frontend#3739] opened 2019-12-29 12:47 UTC
**Describe the bug**
I failed to add speaker's info into the new session I've just added for the the FOSSASIA Summit 2020, even with organizer role. Email and other info disappeared, couldn't upload photo either.
![Screen Shot 2019-12-29 at 19 37 48](https://user-images.githubusercontent.com/32028823/71557031-fbf50a80-2a72-11ea-9edc-e6b639e8b745.png)

**Expected behavior**
Be able to add new sessions and speakers again 

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, 10.14.6]
- Browser: Chrome

**Comment by iamareebjamal** [comment] 2019-12-29 14:09
@kushthedude Is this duplicate of #3731 ?

**Comment by kushthedude** [comment] 2019-12-30 00:21
> @kushthedude Is this duplicate of #3731 ?

No, Also its been quite a time I have not used the following functionality. I will look into it today.

**Comment by kushthedude** [comment] 2019-12-30 02:10
@iamareebjamal Please dont make release, let me  test it more with more number of fields.

**Comment by edenyay** [comment] 2020-01-11 14:15
problem re-exists since yesterday: organizers can add new sessions but cannot speakers details.

**Comment by kushthedude** [comment] 2020-01-23 13:17
@edenyay Solved with a new release made.
Please re-open if it occurs again on production.

**Closed by kushthedude** 2020-01-23 13:17 UTC
Labels: Priority: High, Priority: Urgent, bug
