### ISSUE TITLE
Wizard: Event Description does not take line breaks and paragraphs

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3685] opened 2019-12-06 02:16 UTC
Line breaks and paragraphs are deleted if users save an event. Some events show linebreaks. It is unclear why it still works for some.

Please ensure that line breaks and paragraphs work in all description forms in wizard step 1.

![Screenshot from 2019-12-06 02-58-00](https://user-images.githubusercontent.com/1583873/70289985-cf810200-17d6-11ea-8654-99ebeceeb9b5.png)

**Comment by maze-runnar** [comment] 2019-12-06 11:37
@iamareebjamal @mariobehling i want to take look of this.

**Comment by kushthedude** [comment] 2019-12-06 17:03
Duplicate of #3419

**Closed by kushthedude** 2019-12-06 17:03 UTC
Labels: bug
