### ISSUE TITLE
Sessions are not showing up under "My Sessions"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1943] opened 2019-01-22 10:28 UTC
Expected is: That sessions show up with an info about the state (pending, rejected, accepted etc.) under the "My Sessions Tab".

![screenshot from 2019-01-22 11-24-19](https://user-images.githubusercontent.com/1583873/51529334-c2665900-1e38-11e9-9262-5fe963f03ffd.png)

Even though a session exists, currently it does not show up on the tab for upcoming events.

![screenshot from 2019-01-22 11-26-49](https://user-images.githubusercontent.com/1583873/51529365-d01bde80-1e38-11e9-8f27-f44b0d1f110b.png)

**Comment by Anupam-dagar** [comment] 2019-01-22 16:23
@mariobehling I would like to work on it.

**Comment by mariobehling** [comment] 2019-01-23 16:27
Unfortunately now the "Past Sessions" also disappeared.

![screenshot from 2019-01-23 16-58-25](https://user-images.githubusercontent.com/1583873/51621117-1a35ba80-1f34-11e9-82be-23879bbbd620.png)

**Comment by uds5501** [comment] 2019-01-24 21:17
@mariobehling I can positively confirm that this issue is also a part of #1912.
I shall submit a PR soon (in WIP condition) to explain the situation.

**Comment by uds5501** [comment] 2019-01-28 14:41
@mariobehling I believe the sessions would only show up once they have been scheduled by the organiser (Observed this behaviour while triaging #1912 ), because once the session has been scheduled by the organiser, only then it gets `startsAt` and `endsAt` attributes in it, otherwise during session creation, the model design forces it to be initialised as `null` . 

I guess this should indeed be the intended behaviour, because a session should only show up in the list after it has been scheduled.

@CosmicCoder96 @ritikamotwani , Kindly look into it and close this accordingly

**Comment by CosmicCoder96** [comment] 2019-01-28 14:49
@uds5501 It's a valid issue, albeit it's a bit complicated, the server fails to relate session to you when you are a co-speaker of the session, it gets listed in only the creator's my sessions tab. 
And no, all sessions whether pending or rejected should show up in the my sessions tab.

**Comment by CosmicCoder96** [comment] 2019-02-01 02:49
Fixed in https://github.com/fossasia/open-event-server/pull/5568

**Closed by CosmicCoder96** 2019-02-01 02:49 UTC
Labels: bug
