### ISSUE TITLE
Organizer Speakers List Page: Clicking between filter options like All, Accepted, Confirmed etc. results in Speakers Feature button changes

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4822] opened 2020-08-20 10:45 UTC
The feature button position changes if the organizer clicks around and changes the filter like All, Accepted, Rejected etc.

Compare https://eventyay.com/events/16fa59c7/speakers/all

![Screenshot from 2020-08-20 12-42-19](https://user-images.githubusercontent.com/1583873/90760962-f2126700-e2e2-11ea-8885-bd1514e3d6e6.png)

**Comment by iamareebjamal** [comment] 2020-08-20 10:59
Can't reproduce but will check more thoroughly in August Sprint

**Comment by maze-runnar** [comment] 2020-09-01 10:49
It's correct, not changing, not able to reproduce this.

**Comment by maze-runnar** [comment] 2020-09-01 10:52
Actually when featured speaker is turned off, and after changing tab we came back to same page it switch back to on in UI but it's no actually on, after refreshing the page it returned to off.

**Comment by iamareebjamal** [comment] 2020-09-01 11:11
I recently fixed it. Can you confirm it on latest development branch?

**Comment by maze-runnar** [comment] 2020-09-01 11:56
yeah the issue is resolved.

**Comment by iamareebjamal** [comment] 2020-09-01 12:58
Fixed in #4912

**Closed by iamareebjamal** 2020-09-01 12:58 UTC
Labels: Priority: High, bug
