### ISSUE TITLE
Wizard Step 1: Cannot save (Publish) after adding Stripe - Error "Object not found"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3523] opened 2019-09-17 00:45 UTC
After adding Stripe payment gateway in wizard step 1, it is not possible to publish the event as it shows "Object Not Found"

![Screenshot from 2019-09-17 02-43-01](https://user-images.githubusercontent.com/1583873/65002646-2fad8980-d8f5-11e9-8b68-241aae4a9b0a.png)

**Comment by kushthedude** [comment] 2019-09-17 02:34
Looking into it

**Comment by mariobehling** [comment] 2019-11-09 22:28
Error is: Missing url param: "client_id". (Looked for: property named "clientId".. Please try again

**Comment by mariobehling** [comment] 2019-11-09 22:30
![Screenshot from 2019-11-09 23-27-37](https://user-images.githubusercontent.com/1583873/68535836-f7508780-0348-11ea-81eb-95bc2a7c9929.png)

**Comment by kushthedude** [comment] 2019-11-09 22:43
We debugged the cause for it development env and it was due to clientID not
flowing.
The following didnt occur on production at that time, will check into it
again.

**Comment by prateekj117** [comment] 2019-11-12 18:50
@kushthedude Are you working on this? This seems urgent.

**Comment by kushthedude** [comment] 2019-11-13 03:18
Yes, I am still on it.

**Comment by mariobehling** [comment] 2019-11-25 06:13
I tried connecting the Stripe Account. It is possible now to open and connect the account, but when I hit "Publish" it shows "Object not found."

**Comment by prateekj117** [comment] 2019-11-25 16:29
@kushthedude What's the update on this?

**Comment by iamareebjamal** [comment] 2019-11-25 21:16
/v1/stripe-authorization throws 404

**Comment by kushthedude** [comment] 2019-11-25 21:20
@iamareebjam since he was able to connect the account successfully then how
can authorisation throw 404

**Comment by iamareebjamal** [comment] 2019-11-25 21:25
![](https://files.gitter.im/fossasia/eventyay-devops/oZb7/Screenshot-from-2019-11-25-19-35-19.png)

If I had the answer to it, I would have written that here instead

**Comment by iamareebjamal** [comment] 2019-11-26 05:43
For a very strange and bizarre reason, the stripe authorization is not made when I connect to stripe, but when I publish the event. Any reason for this @kushthedude?

And I have confirmed it to be the case. Stripe authorization is not working

**Comment by kushthedude** [comment] 2019-11-26 05:47
> For a very strange and bizarre reason, the stripe authorization is not made when I connect to stripe, but when I publish the event. Any reason for this @kushthedude?
> 
> And I have confirmed it to be the case. Stripe authorization is not working. It's throwing 404

Stripe is not working on the development instance. As the keys are not flowing through the torii. But as eventyay is considered, stripe should work smoothly as its on production. I will check into it again later today

**Comment by iamareebjamal** [comment] 2019-11-26 05:56
> But as eventyay is considered, stripe should work smoothly as its on production.

How can you just assume it is working?

I just confirmed the bug locally as well

**Comment by iamareebjamal** [comment] 2019-11-26 06:04
Happening due to this: https://github.com/fossasia/open-event-server/pull/6277

Revert the decorators and confirm everything is working. Then, I'll make a minor release today

**Comment by prateekj117** [comment] 2019-11-28 15:02
@iamareebjamal So should we close this?

**Comment by iamareebjamal** [comment] 2019-11-28 16:16
After it is confirmed to be solved

**Closed** 2019-11-28 17:27 UTC
Labels: Priority: High, Priority: Urgent, bug, codeheat
