### ISSUE TITLE
Password input box width greater than login card

### ISSUE THREAD

**Issue by pc-beast** [fossasia/open-event-frontend#7155] opened 2021-04-21 03:37 UTC
**Describe the bug**

Width of password input box is greater than the whole login card between 995px to 1200 px

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://eventyay.com/login'
2. Change you window width to anywhere in between 995px to 1200px
3. See error

**Expected behaviour**

Both email and password input boxes should have the same width.

**Screenshots**

![Screenshot from 2021-04-21 09-00-03](https://user-images.githubusercontent.com/56963647/115493142-cc2dcf80-a280-11eb-9142-52fc7132800a.png)

**Desktop:**
 - OS: Ubuntu
 - Browser: Chrome

**Comment by anshdhinhgra47** [comment] 2021-04-21 07:21
Could I work on this issue ?

**Comment by supzi-del** [comment] 2021-04-26 18:42
Can I work on this?

**Comment by abhaysinghs772** [comment] 2021-05-02 20:34
hey @pc-beast  I am a beginner and want to work on this issue.
can I work on this issue.

**Comment by sans2801** [comment] 2021-05-05 04:00
Hello @pc-beast I'd like to know if the issue is still open

**Comment by pc-beast** [comment] 2021-05-05 05:23
Yes the issue is open, and anyone can work on it.

**Comment by iamdevvalecha** [comment] 2021-05-06 17:32
unable to reproduce

**Comment by pc-beast** [comment] 2021-05-06 17:35
> unable to reproduce

issue is still there...read steps carefully

**Comment by sans2801** [comment] 2021-05-07 07:43
Yes sir @pc-beast, working on it

**Comment by ambivert-sam** [comment] 2021-05-18 07:53
Would love to work on this issue, will you please assign it to me?

**Comment by iamdevvalecha** [comment] 2021-05-18 08:03
@ambivert-sam their is already a pr.

**Comment by iamdevvalecha** [comment] 2021-05-25 01:21
@MeghalBisht di please, close this issue.

**Closed** 2021-05-25 03:09 UTC
Labels: bug
