### ISSUE TITLE
Display location of the event in the "Getting Here" Map

### ISSUE THREAD

**Issue by DinDev3** [fossasia/open-event-frontend#3707] opened 2019-12-20 13:58 UTC
**Problem**
The "Getting Here" map always displays the North American map, regardless of the address of the event.

**Suggested Solution**
Drop a pin and display the proper location that's given as the address of the event location in the "Getting Here" map.

**Alternative Solution**
Re-centre the map to the country in which the event is expected to take place in.

---
Displayed below in the screenshot is an example of what I suggest as a solution.
![image](https://user-images.githubusercontent.com/47103883/71259390-5ea52280-235e-11ea-85c4-caea9b7060d0.png)

**Comment by prateekj117** [comment] 2019-12-20 14:00
Duplicate of #3563.

**Closed by prateekj117** 2019-12-20 14:00 UTC

**Comment by kushthedude** [comment] 2019-12-25 05:04
Duplicate of #3563
