### ISSUE TITLE
Groups: Event owners are not able to add events to their groups

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#7181] opened 2021-04-27 07:35 UTC
Event owners are not able to add or edit their groups. The user group “capeITEvents” is not able add events to the group. It shows an error "Event Owner Access Required", but the user is the actual owner.

**Comment by sachinchauhan2889** [comment] 2021-04-27 10:23
i tried. not able to reproduce the issue.

Not getting any error if user is owner of event. user able to add his owned events.

Only Getting error("event owner access is required") when user is only organiser of event.

**Comment by faisalkhandholpur** [comment] 2021-05-02 07:58
I can handle this issue . Please assign this issue to me.

**Closed** 2021-05-04 14:23 UTC
Labels: Priority: High, Priority: Urgent, bug, next step
