### ISSUE TITLE
Add "checkbox" type for custom form field in attendee form section. 

### ISSUE THREAD

**Issue by mayan-sharma** [fossasia/open-event-frontend#6504] opened 2021-01-27 15:39 UTC
Currently, there are two options: "Text" and "Number" for the custom form field type in the information to collect section in the attendee form while creating an event.

I would like to add a "Checkbox" type to get the consent of an attendee to receive emails for other events, etc. 

![Screenshot (47)](https://user-images.githubusercontent.com/41385368/106014016-0c970a80-60e3-11eb-8eb8-e97a293dbd56.png)

**Comment by MeghalBisht** [comment] 2021-01-27 15:57
duplicate of #5833

**Closed** 2021-01-27 16:02 UTC

**Comment by mayan-sharma** [comment] 2021-01-27 16:07
> duplicate of #5833

Thanks for telling, I didn't see that before.
