### ISSUE TITLE
Session Create 'Slide' Input box not working

### ISSUE THREAD

**Issue by bhaveshAn** [fossasia/open-event-frontend#1095] opened 2018-05-04 17:30 UTC
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**

On Creating sessions `slide` input box not working.

**Expected behavior:**

'Slide' Input box should work.

**Steps to reproduce:**

Create an event and goto `/events/:event_id/sessions/create`
Enter values for Slide Input.

**Related code:**

```
insert any relevant code here else remove this section
```

**Other information:**

**System information:** 

```
Your operating system
```

```
output of `node -v`
```

```
output of `npm ls ember-cli`
```

**Would you like to work on the issue?**

**Comment by CosmicCoder96** [comment] 2018-06-30 23:04
duplicate of #1290

**Closed by CosmicCoder96** 2018-06-30 23:04 UTC
