### ISSUE TITLE
Uneven image sizes in the featured speaker section

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-frontend#3439] opened 2019-08-18 10:42 UTC
https://eventyay.com/e/a8b7e1b2
![image](https://user-images.githubusercontent.com/27783786/63223436-e6252e00-c1d2-11e9-99ce-f3bdc5a060b3.png)

**Comment by mrsaicharan1** [comment] 2019-08-18 11:02
@liveHarshit This is not a bug. Rather a feature where the cropping tool should be integrated with the speaker image.  These are in alignment with Semantic UI. Closing this therefore.

**Closed by mrsaicharan1** 2019-08-18 11:02 UTC

**Comment by liveHarshit** [comment] 2019-08-18 11:03
> Rather a feature where the cropping tool should be integrated

But there is no cropping tool integrated.

**Comment by mrsaicharan1** [comment] 2019-08-18 11:05
> > Rather a feature where the cropping tool should be integrated
> 
> But there is no cropping tool integrated.

That's my point. It's a feature which is not of priority here in FE right now. As soon as the high priority issues are taken care of, we'll have a look at this. Letting this stay closed for now.
