### ISSUE TITLE
No error shown when image upload fails

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4222] opened 2020-03-12 06:17 UTC
No error is shown to the user when image upload fails and it also shows new image instead of old image, which is really confusing

**Comment by sandeepbise** [comment] 2020-05-17 15:33
can i solve this one

**Comment by iamareebjamal** [comment] 2020-05-17 15:38
Go ahead

**Comment by khushboogupta13** [comment] 2020-06-18 15:04
can i work on this issue? since I am contributing for the first time can someone guide me through this please?

**Comment by spy-1234** [comment] 2020-06-23 05:20
> can i solve this problem. As I am a first time to contribute in open source

**Comment by iamareebjamal** [comment] 2020-06-23 07:57
Go ahead

**Comment by amanprateek123** [comment] 2020-09-05 10:20
@iamareebjamal  If the issue is not assigned to anyone yet,then please assign this issue to me.I want to contribute in open source. And, since I am new to this repo, please guide me through

**Comment by iamareebjamal** [comment] 2020-09-05 10:28
Go ahead

**Comment by amanprateek123** [comment] 2020-09-05 10:51
@iamareebjamal  Thank you for assigning me. But, can u please give me some guidence as I am new to this repo.

**Comment by iamraghs** [comment] 2020-10-29 07:21
can i solve this issue ...

**Comment by JainJai2305** [comment] 2020-10-30 07:48
Hi, allow me to solve this issue

**Comment by mariobehling** [comment] 2020-11-01 13:50
@iamraghs Please go ahead.

**Comment by namanjain007** [comment] 2020-11-08 07:03
![Screenshot from 2020-11-08 12-31-09](https://user-images.githubusercontent.com/31573807/98459188-50523600-21be-11eb-967d-94337c41a482.png)
In Components/widgets/forms/image-upload.js
why is this callback function not handeling the error ?

**Closed** 2020-11-13 03:24 UTC
Labels: Priority: High, bug, project
