### ISSUE TITLE
Unable to add line breaks in event description

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-frontend#3419] opened 2019-08-15 13:05 UTC
**Describe the bug**
Adding line breaks in event description doesn't work. It still appears in the same line in the event page.

**To Reproduce**
Try adding multiple paragraphs in event description.

**Comment by Dishebh** [comment] 2020-03-20 08:01
Is the issue valid? Unable to reproduce it.

**Comment by iamareebjamal** [comment] 2020-03-20 13:55
What did you to reproduce it? And please either close your PRs or complete them before working on other issues

**Comment by Dishebh** [comment] 2020-03-20 14:50
> What did you to reproduce it? And please either close your PRs or complete them before working on other issues

Roger.

**Comment by iamareebjamal** [comment] 2020-03-20 15:31
Roger
What did you do to reproduce it?

**Comment by Dishebh** [comment] 2020-03-20 15:50
> Roger
> What did you do to reproduce it?

Created an event and added some paragraphs in event description.They were still distinguishable even after saving it.

**Comment by iamareebjamal** [comment] 2020-03-20 15:54
>  It still appears in the same line in the event page.

Show the screenshot of event page

**Comment by Dishebh** [comment] 2020-03-20 17:08
> > It still appears in the same line in the event page.
> 
> Show the screenshot of event page

![Screenshot from 2020-03-20 22-37-18](https://user-images.githubusercontent.com/43489708/77188105-804bac80-6afb-11ea-8b0b-dd20e5381c64.png)

**Comment by iamareebjamal** [comment] 2020-10-06 03:23
Fixed in #5193 
Duplicates: #4542 #5178

**Closed by iamareebjamal** 2020-10-06 03:23 UTC
Labels: Priority: High, bug, codeheat
