### ISSUE TITLE
Hide tabs in side menu on public route if no data is present

### ISSUE THREAD

**Issue by pradeepgangwar** [fossasia/open-event-frontend#1243] opened 2018-06-05 07:22 UTC
**Describe the bug**
Currently speakers and sessions are visible in side menu even if there are no entries for that. We should not be showing this unless we have approved speakers and sessions.

**Comment by CosmicCoder96** [comment] 2018-06-07 08:26
duplicate of #650

**Closed by CosmicCoder96** 2018-06-07 08:26 UTC
Labels: has-PR
