### ISSUE TITLE
Attendee Export: CSV/PDF does not include all the questions set on the attendee form (Wizard step 3)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5643] opened 2020-11-15 14:30 UTC
We have the option to add questions to the attendee form in the wizard step 3. Currently this information is only shown on the personal ticket order page. 

We need this information to be available on the Export File of the CSV and PDF. 

Compare to the Techcul event and export from the attendee page: https://eventyay.com/e/ae73f280

![Screenshot from 2020-11-15 15-29-35](https://user-images.githubusercontent.com/1583873/99187524-6a0ff200-2757-11eb-98c6-65a7b372777f.png)

**Comment by iamareebjamal** [comment] 2020-11-15 14:37
Duplicate of #4615? 

I just exported the CSV and PDF and it has both the questions 
![image](https://user-images.githubusercontent.com/3874064/99187718-3eecc900-277e-11eb-9c38-54d42e5e3822.png)

**Comment by mariobehling** [comment] 2020-11-15 14:39
@hpdang Did you try again? Please check.

**Comment by hpdang** [comment] 2020-11-15 14:49
Works, closed the ticket now

**Comment by hpdang** [comment] 2020-12-03 09:14
Data is still missing in one required field. When I download attendees csv for this event https://eventyay.com/events/ae73f280, Job Title column is completely empty even though it is one of required field in the ticket form. See below: 

![Screenshot from 2020-12-03 10-08-58](https://user-images.githubusercontent.com/1658742/100988724-508ce980-3550-11eb-8ecb-081c3a505691.png)

**Closed** 2020-12-03 10:07 UTC
Labels: Priority: High, bug
