### ISSUE TITLE
Not able to crop the image for the uploaded image while creating the event

### ISSUE THREAD

**Issue by indavarapuaneesh** [fossasia/open-event-frontend#4931] opened 2020-09-01 14:10 UTC
**Describe the bug**

When I tried to upload a photo while trying to create an event, I am unable to crop the uploaded image.
**To Reproduce**
1. login to create an event
2. Click on create an event
3. upload photo larger than recommended

**Expected behavior**

should be able to crop the photo which is bigger than recommended.
**Screenshots**

![bug](https://user-images.githubusercontent.com/34550287/91861743-cc923f80-ec8a-11ea-8165-4fd009a24bdd.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Browser : firefox
 - Version : 80

**Comment by iamareebjamal** [comment] 2020-09-01 14:13
What is the error you're getting

**Comment by indavarapuaneesh** [comment] 2020-09-01 14:14
not able to crop the image. can't see the whole cropping window. Can't displace it.

**Comment by iamareebjamal** [comment] 2020-09-01 14:29
Duplicate of #4716

**Closed by iamareebjamal** 2020-09-01 14:29 UTC
