### ISSUE TITLE
Too many steps to update profile image

### ISSUE THREAD

**Issue by Batey96** [fossasia/open-event-frontend#3565] opened 2019-10-19 13:30 UTC
**Is your feature request related to a problem? Please describe.**

For an update(change) of profile image,the user is forced to first delete(and confirm delete) the present image before uploading another.The steps(3 steps) here are:
**1)Delete**
**2)confirm Delete**
**3)file select**
**4)Update the change**

**present state**

![touchedbug](https://user-images.githubusercontent.com/24868289/67145798-66701a00-f27c-11e9-862d-998725f20ff2.gif)

**Describe the solution you'd like**

The delete buttons should only reset the image to the default avatar displayed on the navbar(assuming the user doesn't want any longer an image as his profile image );
But to change(update) the present image,the user should simply click on the present image and select image from popup fileList.the steps here are:
**1) file select**

![touched](https://user-images.githubusercontent.com/24868289/67145329-aaf9b680-f278-11e9-9fc0-9782c8955859.gif)

@mariobehling  @kushthedude i am already working on this,i claim this issue if it sounds reasonable to you

**Comment by uds5501** [comment] 2019-11-12 18:17
This does look good. have you prepared the PR? @Batey96

**Comment by snitin315** [comment] 2020-01-22 14:01
I am taking this issue.

**Comment by amanprateek123** [comment] 2020-09-05 08:02
@Batey96  If the issue is not assigned to anyone yet,then please assign this issue to me.I want to contribute in open source. And, since I am new to this repo, please guide me through

**Comment by mariobehling** [comment] 2020-11-01 09:56
This issue is not really a bug and works within the scope currently. A better implementation would be nice, but right now it is out of scope. Therefore closing it. Thank you.

**Closed by mariobehling** 2020-11-01 09:56 UTC
