### ISSUE TITLE
Timezone issue prevents changing existing event

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6507] opened 2021-01-28 06:27 UTC
Trying to change an existing event suddenly gives an error message that the time of the ticket is longer than the event. This is not correct as per the below screenshots.

https://eventyay.com/events/a805baab
![Screenshot from 2021-01-28 07-23-06](https://user-images.githubusercontent.com/1583873/106098949-329bc980-613a-11eb-9076-fd301e2e6942.png)
![Screenshot from 2021-01-28 07-22-27](https://user-images.githubusercontent.com/1583873/106098951-33ccf680-613a-11eb-89c3-d920b6c9dbe6.png)
![Screenshot from 2021-01-28 07-21-03](https://user-images.githubusercontent.com/1583873/106098954-33ccf680-613a-11eb-9ba8-d1d71c8520f1.png)

**Comment by iamareebjamal** [comment] 2021-01-28 18:07
Duplicate of #6150

**Closed by iamareebjamal** 2021-01-28 18:07 UTC
Labels: Priority: High, Priority: Urgent, bug
