### ISSUE TITLE
Is the frontend broken?

### ISSUE THREAD

**Issue by Kreijstal** [fossasia/open-event-frontend#1511] opened 2018-07-28 12:08 UTC
**Describe the bug**

I'm getting this issue
**To Reproduce**
1. Update new repo
2. Go to homepage

**Expected behavior**

Front screen shouldn't have an error.
**Screenshots**

![image](https://user-images.githubusercontent.com/2415206/43356352-5bf7481c-9299-11e8-8f58-8103e9e2da4c.png)
**Desktop (please complete the following information):**
 Linux
Chromium

**Comment by srv-twry** [comment] 2018-07-28 14:12
Closing since you've confirmed in the channel that it works.

**Closed by srv-twry** 2018-07-28 14:12 UTC
