### ISSUE TITLE
Canceled orders show up in notifications but not on overview page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3688] opened 2019-12-06 11:35 UTC
Canceled orders can be seen in the notifications panel, but they don't show up on the actual list of canceled tickets.

![Screenshot from 2019-12-06 12-33-58](https://user-images.githubusercontent.com/1583873/70320377-d7679300-1824-11ea-8a23-245936a16798.png)

**Comment by kushthedude** [comment] 2019-12-07 11:43
@iamareebjamal I just noticed a very buggy behaviour rn,
- I paid a pending order with payment due and cancelled the order from the event dashboard.
**After the cancelling, The order showed up like this**
<img width="1331" alt="Screenshot 2019-12-07 at 5 12 43 PM" src="https://user-images.githubusercontent.com/44091822/70374068-d6ae2a00-1914-11ea-9891-39f05c9f7487.png">
<img width="1362" alt="Screenshot 2019-12-07 at 5 12 50 PM" src="https://user-images.githubusercontent.com/44091822/70374069-da41b100-1914-11ea-8708-95cd79d2b7ad.png">

**Comment by uds5501** [comment] 2019-12-22 17:37
@maze-runnar or @Reetam-Nandi you guys might want to try this.

**Comment by maze-runnar** [comment] 2019-12-22 18:42
@uds5501 i am unable to reproduce it . the cancelled order is showing correctly -
![Screenshot from 2019-12-23 00-10-56](https://user-images.githubusercontent.com/56407566/71325851-cacb8600-2518-11ea-8cba-ea961b148255.png)
Can you please check once ?

**Comment by maze-runnar** [comment] 2019-12-23 15:28
@uds5501 @kushthedude once the order is cancelled , Cancel button is still enabled and on click shows the message "your order is cancelled" While it should be disable once order is cancelled ?

**Comment by maze-runnar** [comment] 2019-12-23 15:29
Is it a valid issue to work on ?

**Comment by uds5501** [comment] 2019-12-24 05:55
@maze-runnar It is a valid issue but make sure you open a new issue on this and work on that

**Comment by imrishabh18** [comment] 2020-02-23 14:37
Close this PR the issue is already fixed.

**Comment by snitin315** [comment] 2020-02-23 14:45
First this is an issue not PR. Second provide reference where it fixed?

**Comment by imrishabh18** [comment] 2020-02-23 20:22
@snitin315  Yup, sorry for the mistake. Reference https://github.com/fossasia/open-event-frontend/pull/3720

**Comment by kushthedude** [comment] 2020-02-23 20:37
Read the issue description again!

**Comment by maze-runnar** [comment] 2020-11-03 05:26
@iamareebjamal @mariobehling cancelled orders are showing correctly - 
![scrnli_11_3_2020_10-46-52 AM](https://user-images.githubusercontent.com/56407566/97952391-37fba900-1dc3-11eb-912b-6dec6fd06a14.png)

**Comment by iamareebjamal** [comment] 2020-11-03 06:27
Will reopen if reproduced

**Closed** 2020-11-03 06:27 UTC
Labels: Priority: High, bug, codeheat, project
