### ISSUE TITLE
Minor layout problem in My Tickets page: ticket links badly aligned

### ISSUE THREAD

**Issue by rolandturner** [fossasia/open-event-frontend#6979] opened 2021-03-11 02:50 UTC
**Describe the bug**
When viewing My Tickets, the ticket links are badly aligned

**To Reproduce**
1. Order multiple tickets for upcoming events.
1. Go to https://eventyay.com/my-tickets/upcoming/completed
1. Ticket links (e.g. " Free order #...") are too close to the location line above, or even overlaid on it.
1. Zoom out to 90% (Firefox: Ctrl+mouse-wheel-down)
1. Layout improves

**Expected behaviour**
The ticket links should have the same spacing as for the other lines, and should do so at all zoom levels.

N.B. This is **not** a problem only visible if the browser is zoomed out, it's **improved** if the browser is zoomed out.

**Screenshots**
- ![100%](https://user-images.githubusercontent.com/646827/110728055-4f5a0f80-8257-11eb-94b9-6a7f2322229f.png)
- ![90%](https://user-images.githubusercontent.com/646827/110728043-48cb9800-8257-11eb-8af6-10b1f0e6db43.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Desktop
 - Browser Firefox
 - Version 86.0

**Comment by darshanhande11** [comment] 2021-04-12 04:48
@rolandturner I would like to work on this issue. Please guide me as I am new to open source.

**Comment by rolandturner** [comment] 2021-04-12 12:29
@darshanhande11 You're welcome to work on it but I should point out that my involvement is limited to observing and reporting the problem. Presumably you'll need to first reproduce the problem, then work out how to resolve it.

**Comment by darshanhande11** [comment] 2021-04-13 13:18
@rolandturner Sir, would you please point me to the location of the file for the above webpage inside this repository.

**Comment by iamareebjamal** [comment] 2021-04-13 13:28
@darshanhande11 You have to find that yourself. We don't have the bandwidth to solve the issue for others. Quite simply, if we had time to give you instructions on how to solve the bug, which file and line to fix and what to change, we would have done it ourselves. That would save us more time than transmitting instructions to others on what to do

**Comment by darshanhande11** [comment] 2021-04-13 13:36
@iamareebjamal Sir, I agree. I'll try to do my best : )

**Comment by rolandturner** [comment] 2021-04-14 01:52
@darshanhande11 My involvement in Open Event is limited to observing and reporting problems in and potential new features for actual use. That is, I'm a **user** of Open Event (e.g. at the FOSSASIA Summit), not a developer of it. I've never seen the source code.

I am a developer, but of other things.

FOSSASIA definitely welcomes new contributors, although it sounds as though you're looking for mentorship. I don't know enough about where to direct you, but I'd suggest that you start with:
- [Open Source Developer Guide and Best Practices at FOSSASIA](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/) which anyone working on FOSSASIA code should understand.
- [Coding Programs and Labs](https://fossasia.org/#labs-programs) for information about formal programs that you might find interesting.

**Comment by RitikaGarg-tech** [comment] 2021-07-19 14:38
Sir can i work on this issue...

**Comment by rolandturner** [comment] 2021-07-20 02:52
> Sir can i work on this issue...

You are free to work on any issue at any time.

**Comment by progmatic-99** [comment] 2021-08-06 11:13
@rolandturner Are you still encountering this problem??
If not, then we can close this issue, as I am not able to reproduce this on my firefox browser on arch linux.

**Comment by rolandturner** [comment] 2021-08-08 00:51
It's definitely still wrong:
![Screenshot from 2021-08-08 08-46-42](https://user-images.githubusercontent.com/646827/128617250-5a7e8592-46dd-4e20-a053-6497fd4d980d.png)

Because there are no near-future events that I'm planning to register for, this screenshot was instead taken from https://eventyay.com/my-tickets/past , but the problem is unchanged.

Note that the overlay problem only arises for events that have **all three** of:
1. an "Online Event" tag
2. a free order number; and
3. a location.

With only two of those items the overlay problem doesn't arise, but the layout still looks ugly (inconsistent line spacings).

**Closed** 2021-08-17 13:35 UTC

**Comment by rolandturner** [comment] 2021-08-18 10:19
Note that this problem still exists as described above. If the ticket is closed because a fix has been accepted into the code but not put onto the live site then that's fine, but if it's expected that the ticket is not closed until the live site has been updated then this ticket should be reopened.

**Comment by maze-runnar** [comment] 2021-08-18 10:26
Hey Ronald, changes are not deployed on live site yet.
