### ISSUE TITLE
Ticket Order Page: Ticket order number show 0

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6660] opened 2021-02-10 15:53 UTC
The ticket order number on some ticket order pages show 0.

https://eventyay.com/orders/15e6aa99-d1a4-4cd9-9115-1ccbdb618c7c/view

![Screenshot from 2021-02-10 16-52-27](https://user-images.githubusercontent.com/1583873/107534769-7245c500-6bc0-11eb-9d04-3274b251eb10.png)

**Comment by iamareebjamal** [comment] 2021-02-10 16:59
Duplicate of #5667

**Comment by iamareebjamal** [comment] 2021-02-10 17:00
Also duplicate of #4613

**Closed by iamareebjamal** 2021-02-10 16:59 UTC
Labels: Priority: High, Priority: Urgent, bug
