### ISSUE TITLE
Implement users API at the settings/applications.

### ISSUE THREAD

**Issue by sumedh123** [fossasia/open-event-frontend#857] opened 2017-09-03 06:10 UTC
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![settingsapplications](https://user-images.githubusercontent.com/17925669/30000972-a258cca4-909c-11e7-87c8-1127b4ed4246.png)

**Comment by sumedh123** [comment] 2017-09-03 06:10
Will take this up.

**Comment by CosmicCoder96** [comment] 2017-09-03 06:13
Duplicate of #507

**Closed by CosmicCoder96** 2017-09-03 06:13 UTC
