### ISSUE TITLE
Login page does not redirects back to create event for guest user

### ISSUE THREAD

**Issue by Haider8** [fossasia/open-event-frontend#2370] opened 2019-03-23 18:44 UTC
**Describe the bug**

When the guest user (not logged in) tries to create event, he/she is taken to the login page, but after that, the user is not redirected back to the create event page upon successful login.

**To Reproduce**
1. Go to 'Create event' page when not logged in.
2. Fill the login form with correct credentials.
3. See error

**Expected behavior**

User should be redirected back to the create event page upon successful login.

**Additional context**

Working on it

**Comment by Haider8** [comment] 2019-03-24 17:42
@uds5501 @ritikamotwani The redirects are already implemented, but it only works if we manually enter the url in the address bar. Else create event url is not stored as the previous route and redirect does not work then, like if we click 'Create Event' in the nav-bar. I need some advice on this please.

**Comment by uds5501** [comment] 2019-03-24 18:04
@Haider8 can you kindly point to the file where this redirection has been specified?

**Comment by Haider8** [comment] 2019-03-24 18:24
@uds5501 ```app/routes/application.js```, you can also see ```app/routes/create.js``` if required :)

**Comment by uds5501** [comment] 2019-03-24 18:32
@Haider8 This `previousRouteName` doesn't work in this case because the user was obviously, never directed to `\create` and the last route he/she visited was indeed `\` .

**Comment by Haider8** [comment] 2019-03-24 18:37
@uds5501 Yes, so how can we redirect the user to ```/create```. I mean what can be the potential fix here. I have tried to put anchor tags for the create event page. But that didn't work.

**Comment by uds5501** [comment] 2019-03-24 18:38
@Haider8 That won't help, your previous URL still remains `\`, this should require application level handling. I am reading through and will let you know if I find something

**Comment by Haider8** [comment] 2019-03-24 18:40
@uds5501 Okay, please do let me know.

**Comment by CosmicCoder96** [comment] 2019-03-24 19:56
@Haider8 It's happening because `authenticatedRouteMixin` aborts the transition of the route to create. However, the conditions which define `previousRouteName` are inside the `.then()` block of the transition. Ergo, they are executed only when the transition completes successfully.  If you replicate those conditions, inside a `catch()` block as well, and in principle catch the aborted Transition exception, it will work fine. 

However, I am afraid there is a high chance it will break some other external routing/redirecting feature involving role invites and reset-password for which acceptance tests are not written yet. Hence will come back to this later, maybe in a week.

**Comment by Haider8** [comment] 2019-03-24 20:53
@CosmicCoder96 Thank you :), meanwhile i will try to send PR as per your suggestion.

**Comment by kushthedude** [comment] 2019-04-05 08:10
Copy of #2396  , Please see #2470

**Comment by prateekj117** [comment] 2019-06-03 05:37
@CosmicCoder96 @uds5501 Would like to work on this.

**Comment by kushthedude** [comment] 2019-06-03 05:48
@prateekj117 feel free to work upon AFAIK. , no one is assigned for now

**Comment by CosmicCoder96** [comment] 2019-06-16 07:50
Duplicate of #2396

**Closed by CosmicCoder96** 2019-06-16 07:50 UTC
Labels: bug
