### ISSUE TITLE
Ticket Order: Getting stuck at email form field when starting order as anonymous user

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4735] opened 2020-08-10 10:47 UTC
When a user is not logged in and starts an order as an anonymous user an email form field appears. After the user adds the email a white overlay appears and nothing happens.

Expected: The user should be able to login or get a message to sign up if he/she is not yet registered.

Tested on Chromium on this event https://eventyay.com/e/16fa59c7

![Screenshot from 2020-08-10 12-43-59](https://user-images.githubusercontent.com/1583873/89775156-83295700-db07-11ea-9df4-a5bc6a49d85f.png)

**Comment by iamareebjamal** [comment] 2020-08-10 10:49
Yes, it is duplicate of #4370 which I'm currently fixing

**Closed by iamareebjamal** 2020-08-10 10:49 UTC
Labels: Priority: High, Priority: Urgent, bug
