### ISSUE TITLE
Add bottom margin to event tags in event card

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2346] opened 2019-03-20 10:24 UTC
**Describe the bug**

The tags in event cards shown on homepage are quite close to the bottom boundary of the card. It will be better to add a bottom margin.
Also in the responsive mode, the tags go out of cards.
**To Reproduce**
1. Go to '/'
2. See error

**Expected behavior**

There should be some gap between tags and bottom boundary of card
**Screenshots**

![Screenshot from 2019-03-20 15-47-08](https://user-images.githubusercontent.com/21174572/54677385-c3f68980-4b28-11e9-91f3-2f6580fa551f.png)

![Screenshot from 2019-03-20 16-12-58](https://user-images.githubusercontent.com/21174572/54678481-3700ff80-4b2b-11e9-9303-bcc9733990f7.png)

**Additional context**

I am working on it.

**Comment by mohitm15** [comment] 2019-03-20 12:08
Wants to take this issue
@Anupam-dagar

**Comment by Anupam-dagar** [comment] 2019-03-20 12:12
@mohitm15 I already opnened a PR

**Comment by mohitm15** [comment] 2019-03-20 12:29
@Anupam-dagar that's nice

**Comment by mohitm15** [comment] 2019-03-20 12:39
@Anupam-dagar But this is not showing in my laptop .... even after checking the responsiveness. I attached a screen shot too.

when screen is resized
![Screenshot from 2019-03-20 18-08-52](https://user-images.githubusercontent.com/35539313/54684758-353f3800-4b3b-11e9-87fc-f8ab2e9e85b0.png)

**Comment by uds5501** [comment] 2019-03-20 15:10
@Anupam-dagar @mohitm15 
Reproduce-able in Iphone5/SE and custom 888x888 config
![image](https://user-images.githubusercontent.com/21087061/54695634-54949000-4b50-11e9-8f12-a76147472ec5.png)

**Comment by kushthedude** [comment] 2019-03-22 20:29
@Anupam-dagar isn't it duplicate of #279

**Comment by kushthedude** [comment] 2019-03-22 20:30
I think this should be enhancement of PR #236

**Comment by uds5501** [comment] 2019-03-23 02:54
@kushthedude since #279 has been closed by the owner himself and the issue still persists so no, this isn't a duplicate

**Comment by kushthedude** [comment] 2019-03-23 05:43
I think a PR has been merged for a issue of overflow of text in event card

**Comment by uds5501** [comment] 2019-03-23 05:48
@kushthedude the merge was not for the overflow of the hashtags, which the current issue points out

**Comment by kushthedude** [comment] 2019-03-23 05:49
Cool😁

**Comment by mohitm15** [comment] 2019-04-17 06:35
@Anupam-dagar Are you still on this issue?

**Comment by Anupam-dagar** [comment] 2019-04-17 06:39
This issue needs to be closed by @cosmiccoder96

**Comment by uds5501** [comment] 2019-04-17 06:44
@Anupam-dagar Actually leave it open, just ask @CosmicCoder96 to add a later label on it

**Comment by khushishikhu** [comment] 2020-07-06 15:54
may I work on this issue?

**Comment by kushthedude** [comment] 2020-07-07 01:46
Go ahead and make sure to check if the issue still exists, as we have upgraded the semantic-ui version recently.

**Comment by khushishikhu** [comment] 2020-07-07 11:10
![Capture](https://user-images.githubusercontent.com/65439761/86771437-d5daa380-c06f-11ea-8cde-29115241de61.PNG)

@kushthedude  sir i have made changes by inspecting in padding and i worked even responsive but vendor.css isn't in the development branch.
can you please help me find where i should make this change in code. so that i can make a PR

**Comment by iamareebjamal** [comment] 2020-07-07 12:07
vendor.css is the compiled file. Not the source file. You don't make changes in compiled code, it is autogenerated

**Comment by vikramroy622** [comment] 2020-08-09 06:51
is this issue is open. do i work on this ?

**Closed** 2020-10-14 05:46 UTC
Labels: UI/UX, bug, codeheat, enhancement, responsive-ui, ui
