### ISSUE TITLE
Integrate Sentry APM tracing

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4256] opened 2020-03-23 13:05 UTC
https://docs.sentry.io/performance-monitoring/getting-started/?platform=javascript

**Comment by ibnjunaid** [comment] 2020-03-25 08:41
@iamareebjamal i wanna work on this issue.

**Comment by Dishebh** [comment] 2020-03-25 09:01
> @iamareebjamal i wanna work on this issue. Please assign this to me and since im new to this repo so please guide me through.

No need of assigning, you can take and work on the issue. Go through the readme file and get familiar with the code base of the project. You can ping on the gitter channel, for any doubts and difficulties you face.

**Comment by atulgawhane** [comment] 2020-05-13 11:57
i want to work on this issue

**Comment by Dishebh** [comment] 2020-05-13 12:09
> i want to work on this issue

Go ahead.

**Comment by Anand-Kumar-Singh** [comment] 2020-05-15 13:07
I wanna to work on this issue. Please assign this to me and i am new please guide me

**Comment by Dishebh** [comment] 2020-05-15 13:49
> I wanna to work on this issue. Please assign this to me and i am new please guide me

No need of assigning. Go ahead with the issue. Start with the readme of the repo.

**Comment by THE-VR7** [comment] 2020-05-21 20:12
I am not able to understand what is the issue, can you please explain it .

**Comment by iamareebjamal** [comment] 2020-05-21 20:25
There is a link in the issue description, please read it

**Comment by amit2699** [comment] 2020-06-13 14:25
@iamareebjamal  Can I work on this issue...

**Comment by amit2699** [comment] 2020-06-13 14:26
issue labelled #4256

**Comment by khushboogupta13** [comment] 2020-06-18 15:02
I wanna work on this issue, since I am contributing for the first time can someone guide me through this?

**Comment by Rudresh22** [comment] 2020-06-29 17:56
Hello, I want to work on this issue, but I am unable to understand what the issue is. Can someone guide me through this?

**Comment by codebreakeragr8** [comment] 2020-07-01 14:33
@iamareebjamal I would like to work on this issue.
P.S- The link provided in the issue statement is not working.

**Comment by iamareebjamal** [comment] 2020-07-01 15:56
Fixed

**Comment by codebreakeragr8** [comment] 2020-07-01 17:50
ok

**Comment by ruhci28** [comment] 2020-07-12 04:01
Hye is anyone working on this issue? If not can I tackle this issue .?

**Comment by iamareebjamal** [comment] 2020-07-12 10:23
Go ahead

**Comment by ruhci28** [comment] 2020-07-22 04:00
Hii , @iamareebjamal  can you guide me how should I proceed . I set up the project on my local machine .

**Comment by iamareebjamal** [comment] 2020-07-22 04:21
The steps are written in the link in issue description

**Comment by ruhci28** [comment] 2020-07-22 04:41
can you tell me which file i have to change

**Comment by ruhci28** [comment] 2020-07-22 04:44
Does i have to change app/utils/sentry.js .?

**Comment by iamareebjamal** [comment] 2020-07-22 05:44
sentry.ts

**Comment by ruhci28** [comment] 2020-07-22 13:58
ok Thanks

**Comment by ruhci28** [comment] 2020-07-23 14:44
Hii @iamareebjamal  i am making changes in /app/sentry.ts according to the guiding link . does i am going right .?

**Comment by creatorpiyush** [comment] 2020-07-30 10:08
Hii, anyone working on this project. If not, can I .?

**Comment by iamareebjamal** [comment] 2020-07-30 10:25
Go ahead

**Closed** 2020-08-02 03:05 UTC
Labels: chore, good first issue, help-wanted
