### ISSUE TITLE
Implement user API on settings/applications

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#507] opened 2017-07-19 08:41 UTC
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

![screenshot from 2017-07-19 14-11-02](https://user-images.githubusercontent.com/12807846/28358339-2a2b2972-6c8c-11e7-82f2-03036b0f11f6.png)

**Comment by geekyd** [comment] 2017-07-19 10:10
@niranjan94
Instead of having individual connect buttons for individual links we can have one button that will reduce the number of requests we make to update the links.

**Comment by niranjan94** [comment] 2017-07-19 10:13
Not possible. These connect buttons would actually start an OAuth
authentication flow with that specific social network platform and then
obtain the profile url and tokens from there. And later the token and url
would be passed on to the server.

**Comment by sumedh123** [comment] 2017-07-23 11:50
@geekyd Are you working on this one?

**Comment by niranjan94** [comment] 2017-07-23 11:52
@sumedh123

There is no server support for this yet. So can't be worked upon until done.

**Comment by CosmicCoder96** [comment] 2018-06-30 22:59
duplicate of #695

**Closed by CosmicCoder96** 2018-06-30 22:59 UTC
Labels: api-integration, blocked-by-server, feature
