### ISSUE TITLE
The third party auth is not workinng

### ISSUE THREAD

**Issue by pranav1698** [fossasia/open-event-frontend#1669] opened 2018-09-27 12:44 UTC
**Describe the bug**

The login with google facebook and twitter is not working, 

**To Reproduce**
1. Go to 'login'
2. Click on 'login with facebook or login with google+ or login with twitter'
3. Nothing happens 

**Desktop (please complete the following information):**
 - OS: [ubuntu
 - Version firefox

**Comment by ritikamotwani** [comment] 2018-09-27 13:06
Duplicate of https://github.com/fossasia/open-event-frontend/issues/1423. Hence closing it.

**Closed by ritikamotwani** 2018-09-27 13:06 UTC
