### ISSUE TITLE
Page keeps loading after accepting a session

### ISSUE THREAD

**Issue by ShridharGoel** [fossasia/open-event-frontend#3420] opened 2019-08-15 13:07 UTC
**Describe the bug**
After accepting a session, page keeps showing the loading message until refreshed.

**Comment by kushthedude** [comment] 2019-08-19 06:12
Duplicate of #3436

**Comment by ShridharGoel** [comment] 2019-08-19 06:20
@kushthedude I don't see this mentioned anywhere in that issue.

**Comment by kushthedude** [comment] 2019-08-19 06:32
See point number 5

**Comment by ShridharGoel** [comment] 2019-08-19 06:38
Okay, but when I had used it for my event, the button was working. The problem was that it kept showing the reloading circular progress bar but on refreshing the page, the session showed as accepted.

**Comment by kushthedude** [comment] 2019-08-19 06:44
> Okay, but when I had used it for my event, the button was working. The problem was that it kept showing the reloading circular progress bar but on refreshing the page, the session showed as accepted.

Don't worry, It will be solved in #3436 .

**Comment by shreyanshdwivedi** [comment] 2019-08-19 07:22
@ShridharGoel are you facing this on eventyay.com?

**Comment by kushthedude** [comment] 2019-08-19 07:33
@shreyanshdwivedi Please reopen if the issue is in regards of productions.

**Comment by ShridharGoel** [comment] 2019-08-19 07:38
> are you facing this on eventyay.com?

Yes.

**Comment by shreyanshdwivedi** [comment] 2019-08-19 08:03
Isn't related to issue mentioned by @kushthedude 
This is production issue

**Comment by kushthedude** [comment] 2019-08-20 17:51
Solved after Ember Tables

**Closed by kushthedude** 2019-08-20 17:51 UTC
