### ISSUE TITLE
Wizard: Clicking "Forward" on Existing Events shows "Object not found"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3640] opened 2019-11-19 04:02 UTC
No matter if the user changes or does not change anything in the event wizard, clicking forward on previously existing events results in "Object not found" error message. The user is not able to change the event.

![Screenshot from 2019-11-19 11-57-56](https://user-images.githubusercontent.com/1583873/69115678-5ee2a180-0ac4-11ea-837f-d75006b97aa4.png)

**Comment by kushthedude** [comment] 2019-11-19 13:06
@prateekj117 Can you please check the reproducibility ?

**Comment by prateekj117** [comment] 2019-11-25 16:40
@kushthedude Not producible. @mariobehling Can you share more info on how to reproduce it.

**Comment by iamareebjamal** [comment] 2019-11-25 21:14
/v1/stripe-authorization throws 404

**Comment by iamareebjamal** [comment] 2019-11-29 21:14
Duplicate of #3523

**Closed by iamareebjamal** 2019-11-29 21:14 UTC
Labels: Priority: High, Priority: Urgent, bug
