### ISSUE TITLE
Wrong Event Time on public page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3582] opened 2019-10-30 11:39 UTC
The FOSSASIA page shows the event starts at 4pm. The event time in the wizard is: Start 9AM. I am using a browser in Germany.

Expected: Event time should show correct local time.
![Screenshot from 2019-10-30 12-35-15](https://user-images.githubusercontent.com/1583873/67855112-1f9ee180-fb12-11e9-838d-e483ca401950.png)

Wizard time of the same event:
![Screenshot from 2019-10-30 12-38-25](https://user-images.githubusercontent.com/1583873/67855207-45c48180-fb12-11e9-8d38-b247fb4c06a4.png)

**Comment by maze-runnar** [comment] 2019-10-30 12:01
i want to work on this sir.

**Comment by kushthedude** [comment] 2019-10-30 13:48
> i want to work on this sir.

@maze-runnar You already have issue assigned to you, Please complete those before.

**Comment by iamareebjamal** [comment] 2019-11-01 08:33
@kushthedude Update?

**Comment by DaKeiser** [comment] 2019-11-02 10:07
@kushthedude Can I take this issue ? I guess https://github.com/fossasia/open-event-frontend/pull/3581 would solve the issue temporarily by mentioning the reference of the timezone. Meanwhile I will look into this issue.

**Comment by iamareebjamal** [comment] 2019-11-02 18:15
No, that won't fix the issue. Wrong time is sent on the server, so it is stored incorrectly in the DB

**Comment by kushthedude** [comment] 2019-11-02 18:22
The issue is not related to different locations, server is sending wrong
time. Need to debug from server.

**Comment by iamareebjamal** [comment] 2019-11-02 18:26
server can't send wrong time. It doesn't process time at all. It returns whatever is stored in DB, so there is either a bug in event creation/edit form or event POST method (unlikely)

**Comment by kushthedude** [comment] 2019-11-02 18:33
I will check the creation process and data getting sent to db and get back
to you.

**Comment by mariobehling** [comment] 2019-11-07 04:06
Accessing the site from different timezones shows a different event time. It seems the system takes the time from browser through IP. And there is a conflict in the logic somewhere as the event time should be displayed according to the event time zone instead of the user's time (or the browser).

Same problem with timezone applies to ticket sales time. If I enter ticket sales end 23.59 for the event. Suddenly the live site will display it will end 7 hours later if I am in another time zone.

To keep things simple for now expected is:

Don't adjust according to any timezone of the user or browser. Only display the timezone marked in the wizard step 1 -> event time.

**Comment by ImShashikant** [comment] 2019-11-07 04:21
Hi @mariobehling, may I work on this issue?

**Comment by kushthedude** [comment] 2019-11-07 04:24
@mariobehling I have tried to access the same from different timezones,
time is consistent
 As @iamareebjamal said wrong time is getting stored to Db which I will
check again

**Comment by iamareebjamal** [comment] 2019-11-07 07:24
It is even stored incorrectly in the DB, so it is not just the matter of frontend shifting timezone
event.starts-at is tored as "2020-03-19T08:00:00+00:00" in DB
Which is 4 PM in Singapore Time (+8). So, if it meant to be 9 AM Singapore time, it should be stored as "2020-03-19T01:00:00+00:00" in DB. So it is an issue with saving event wizard

**Comment by kushthedude** [comment] 2019-11-07 07:25
Okay, so it is confirm that event time is not changing with ip location.
its issue with time stamp getting saved by event wizard.

**Comment by iamareebjamal** [comment] 2019-11-07 07:27
@kushthedude It may be doing it according to the browser timezone as well, so it might be a bug there too. IP location != browser timezone. Even if you use VPN, your browser will show same timezone. But as @mariobehling and I both see 4 PM, it is most likely not depending on the timezone of the user

**Comment by iamareebjamal** [comment] 2019-11-07 07:52
When loading the event wizard, it initially shows 8 and 16 to me and then changes it to 13:30 and 21:30. +5:30, so the bug is in the event wizard. First, of all, it should not convert to the user timezone, but the event timezone which is selected in the dropdown, so Singapore. Then, when sending the time to server, it sends the time adjusting to local timezone again, where it should adjust to event timezone
I have corrected the FOSSASIA summit time, but the bug is in event wizard.

**Comment by iamareebjamal** [comment] 2019-11-10 07:46
@kushthedude Update?

**Closed** 2019-11-20 18:40 UTC
Labels: Priority: High, Priority: Urgent, bug
