### ISSUE TITLE
On mobile view menu bar name shows "Open Event" instead of "Eventyay"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3683] opened 2019-12-05 07:32 UTC
The software we develop is called "Open Event". However, the name can be configured in the admin section. On the life deployment we use the name "eventyay". This name shows up on the desktop page, but on the mobile page, the name Open Event shows up.

![Screenshot_20191205_082736_com android chrome](https://user-images.githubusercontent.com/1583873/70213579-f1787700-1739-11ea-8f09-2cb6eeb7c5d8.jpg)

**Comment by milekag01** [comment] 2019-12-05 12:54
@mariobehling can I resolve this bug?

**Comment by prateekj117** [comment] 2019-12-05 13:00
@milekag01 Go ahead.

**Comment by kushthedude** [comment] 2019-12-05 13:26
Duplicate of #3620

**Closed by kushthedude** 2019-12-05 13:26 UTC
Labels: bug
