### ISSUE TITLE
Display example@example.com as my profile email

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#6898] opened 2021-03-03 12:27 UTC
I logged in to my account after clicking around for a bit, my profile switched to example@example.com as my profile display. I don't know what happened. 

![Screenshot from 2021-03-03 13-19-43](https://user-images.githubusercontent.com/1658742/109805720-1650e800-7c24-11eb-9676-4278e594cf6d.png)

**Comment by iamareebjamal** [comment] 2021-03-03 14:20
Duplicate of #6885

**Closed by iamareebjamal** 2021-03-03 14:20 UTC
