### ISSUE TITLE
Ticket table on public event page not fully responsive

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4118] opened 2020-02-19 03:16 UTC
On the public event page the ticket table is not adapted fully to mobile screens. Please implement the table for a good mobile user experience.
![Screenshot_20200219_110645_com android chrome](https://user-images.githubusercontent.com/1583873/74798652-46736480-5309-11ea-8c11-e21942e3a9a3.jpg)

**Comment by snitin315** [comment] 2020-02-19 03:32
Duplicate #3812

**Comment by kushthedude** [comment] 2020-02-19 07:17
Duplicate of #3511

**Closed by kushthedude** 2020-02-19 07:17 UTC
Labels: bug
