### ISSUE TITLE
Sometimes, eventyay page doesn't show anything but error message

### ISSUE THREAD

**Issue by anhanh11001** [fossasia/open-event-frontend#3405] opened 2019-08-14 02:57 UTC
**Describe the bug**
Sometimes, when going to eventyay.com, I got this error. It is occasional, not really often. If I open an icognito or another browser then the page is working normally

**Screenshots**
<img src="https://i.ibb.co/BNpKnJn/image.png" alt="image" border="0">

**Desktop (please complete the following information):**
Chrome

**Comment by kushthedude** [comment] 2019-08-14 04:00
Duplicate of #3262

**Closed by kushthedude** 2019-08-14 04:00 UTC
