### ISSUE TITLE
Sessions entry clipped in Firefox for Android

### ISSUE THREAD

**Issue by mishari** [fossasia/open-event-frontend#7034] opened 2021-03-20 01:45 UTC
When I go through the list of sessions in firefox for android, it's clipped on the right, scrolling is locked so I can't see the full information. I need to enable "request desktop site" in order to see the full entry".

**Comment by RiyaGupta89** [comment] 2021-08-20 03:58
@mishari  Please share ss for describing more.

**Comment by pc-beast** [comment] 2021-08-20 04:18
It looks duplicate of #6761 which are closed in #7467 @maze-runnar this could be closed now

**Closed** 2021-08-20 06:31 UTC
Labels: bug
