### ISSUE TITLE
Add Currency symbol in items total of Add Order section 

### ISSUE THREAD

**Issue by harsh-jindal** [fossasia/open-event-frontend#2224] opened 2019-02-22 20:56 UTC
**Describe the bug**

NO Currency symbol in items total of Add Order section 
**To Reproduce**
1. Go to 'Tickets'
2. Click on 'Add order'

**Expected behavior**

Currency symbol in items total of Add Order section 
**Screenshots**

![screenshot 2019-02-23 at 2 25 38 am](https://user-images.githubusercontent.com/31013104/53270661-56fef800-3712-11e9-964e-900cd80639da.png)

**Additional context**

I'm working on it.

**Comment by shreyanshdwivedi** [comment] 2019-03-18 14:52
@harsh-jindal if you are not workin on this, I'll take it up.

**Comment by harsh-jindal** [comment] 2019-03-19 02:15
@shreyanshdwivedi You can take this up.

**Comment by mohitm15** [comment] 2019-03-25 07:11
@harsh-jindal Do we need to create a new event for that???
   Because I am getting currency symbols in previously made events??
![Screenshot from 2019-03-25 12-40-04](https://user-images.githubusercontent.com/35539313/54900987-31286700-4efb-11e9-8812-3ac4397eadd3.png)

Attached is the screenshot

**Comment by mohitm15** [comment] 2019-03-25 07:36
@shreyanshdwivedi how can I review this issue ??

**Comment by shreyanshdwivedi** [comment] 2019-03-25 07:43
@mohitm15 this issue is duplicate of https://github.com/fossasia/open-event-frontend/issues/2223 and someone else is working on it.
@harsh-jindal please close this issue

**Comment by mohitm15** [comment] 2019-03-25 08:26
@shreyanshdwivedi that's what I am talking about

**Comment by mohitm15** [comment] 2019-03-25 13:34
I think this issue needs to be resolved than that of #2223 .

**Closed** 2019-03-25 13:37 UTC
