### ISSUE TITLE
Adding list of ISD codes for the phone field

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2894] opened 2019-05-11 22:45 UTC
**Is your feature request related to a problem? Please describe.**

Addition of list having ISD codes  corresponding to the country's abbreviation in the phone field

**Describe the solution you'd like**

added a drop-down list

**Additional context**

working on it

**Comment by ritikamotwani** [comment] 2019-05-12 03:55
Duplicate of https://github.com/fossasia/open-event-frontend/issues/2578

**Closed by ritikamotwani** 2019-05-12 03:55 UTC
