### ISSUE TITLE
Getting Here link directs to bottom of page instead of top of map

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1797] opened 2019-01-14 20:22 UTC
Expected "Getting Here" link directs to top of map.

Please also test "Getting Here" link for subpages. It does not direct to map area from subpages neither.

![screenshot from 2019-01-14 21-21-32](https://user-images.githubusercontent.com/1583873/51138844-87659380-1842-11e9-9209-1b9bd637106e.png)

**Comment by sk9331657** [comment] 2019-01-15 14:36
@mariobehling  Claiming this.

**Comment by uds5501** [comment] 2019-01-29 17:32
@sk9331657 if you are not working on this can i give it a try?

**Comment by kushthedude** [comment] 2019-04-09 15:04
@mariobehling @CosmicCoder96 I think this is duplicate of #275

**Comment by kushthedude** [comment] 2019-06-10 06:15
Duplicate of #275

**Closed by kushthedude** 2019-06-10 06:15 UTC
Labels: bug
