### ISSUE TITLE
bug: css overflow of ticket table on small screen devices

### ISSUE THREAD

**Issue by snitin315** [fossasia/open-event-frontend#3812] opened 2020-01-16 09:32 UTC
**Describe the bug**

If  `Ticket type text` is long then there is overflow of content outside the table.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [https://eventyay.com/e/fb25b5fd](https://eventyay.com/e/fb25b5fd)
2. Scroll down to order ticket table.
2. Inspect responsiveness

**Expected behaviour**
content must not overflow.

**Screenshots**
![Screenshot from 2020-01-16 14-53-35](https://user-images.githubusercontent.com/46647141/72511235-d5a3dd00-3870-11ea-8516-c65b342ef6ad.png)

**Smartphone (please complete the following information):**
 - Device: `I phone 6/7/8` and more ...
 - Browser  : All

**Additional context**
Please Check if the issue is valid. If so  I would like to work on this.

**Comment by kushthedude** [comment] 2020-02-19 07:17
Duplicate of #3511

**Closed by kushthedude** 2020-02-19 07:17 UTC
