### ISSUE TITLE
Call for Speakers "Login" should direct back to "CfS" page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3673] opened 2019-11-29 19:56 UTC
It a speaker goes to the page of a call for speakers, they are requested to login. If the speaker logs in they are redirected to the frontpage.

EXPECTED: Instead they should be redirected back to the call for speakers page.

1. The call for speakers page:
![Screenshot from 2019-11-29 20-53-09](https://user-images.githubusercontent.com/1583873/69888139-a0582580-12ea-11ea-8832-0b4200b6a4fa.png)

2. Requires login
![Screenshot from 2019-11-29 20-53-22](https://user-images.githubusercontent.com/1583873/69888146-a817ca00-12ea-11ea-87a3-abae4ef18e14.png)

3. Login takes place
![Screenshot from 2019-11-29 20-53-47](https://user-images.githubusercontent.com/1583873/69888155-b2d25f00-12ea-11ea-8828-5b4457ebff3e.png)

4. Speaker is now redirected to front page.
EXPECTED: Redirect back to CfS page.

**Comment by iamareebjamal** [comment] 2019-11-29 21:10
Right now, there is no functionality of redirecting to the last page user was on prior to login, which is a very bad UX. Simply adding the behaviour will solve this issue

**Comment by kushthedude** [comment] 2019-12-01 08:25
> Right now, there is no functionality of redirecting to the last page user was on prior to login, which is a very bad UX. Simply adding the behaviour will solve this issue

We are using `Ember-Auth` for the all login related purpose and to the same, this feature is already implemented in the library. There is something wrong in our implementation, which may require some debugging.

**Comment by iamareebjamal** [comment] 2019-12-01 10:03
Duplicate of #2396

**Comment by iamareebjamal** [comment] 2019-12-01 10:03
We don't close old issues or else conversation is lost as has been in some of the previous issues

**Closed by iamareebjamal** 2019-12-01 10:03 UTC
Labels: Priority: High, bug
