### ISSUE TITLE
Switch buttons: Cannot unswitch buttons

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5238] opened 2020-10-04 17:45 UTC
Switch buttons can only be switched "on". 
* It is not possible to switch them off.
* When one button is switched on, the second button e.g. Promoted event is also switched on

Compare: https://eventyay.com/admin/events/

![Screenshot from 2020-10-04 19-42-37](https://user-images.githubusercontent.com/1583873/95022894-1e5b2a80-067a-11eb-9645-40dc70299080.png)

**Comment by chauhan0707** [comment] 2020-10-04 21:11
Sir, can I plz work on this issue?

**Comment by Raunaksingh100** [comment] 2020-10-05 01:13
> Sir, can I plz work on this issue?

Go ahead

**Comment by iamareebjamal** [comment] 2020-10-05 10:45
The problem is with ember-source > 3.20.3
I don't know what changed. 

This was fixed in #4912 (#4873) but recent PRs of dependabot I merged added the bug again

So, we need a test which fails on later ember versions so that we don't accidentally merge the PR. I also explored options to use a different switch component but something was still not working.

So, we divide this issue in 3 steps:

- [ ] Revert to ember 3.20.3
- [ ] Create a test to check switch behaviour
- [ ] Move to another switch component which works on new ember versions
- [ ] Upgrade to latest ember

**Comment by chauhan0707** [comment] 2020-10-05 13:05
So is this issue still open or not.

**Comment by iamareebjamal** [comment] 2020-10-05 13:13
Green means open

**Comment by AdityaTeltia** [comment] 2020-10-05 19:02
Can i work on it please ?

**Comment by iamareebjamal** [comment] 2020-10-06 00:34
@chauhan0707 Are you working on it?

**Comment by chauhan0707** [comment] 2020-10-06 04:59
@iamareebjamal sir how can I look into https://eventyay.com/admin/events/ and make any changes. I'm trying to change the code but I want to see the exact toggle switch problem. Sorry for this. Can u help me?

**Comment by iamareebjamal** [comment] 2020-10-06 05:02
1. See above comments, the switch problem has been solved. Remaining 3 points need to be solved. 
2. You are not admin of eventyay, you cannot access that page. Deploy the server locally and check admin pages

**Comment by daretobedifferent18** [comment] 2020-10-23 16:37
I want to work on this issue if no one is working on it.

**Comment by sansyrox** [comment] 2020-10-26 12:40
I'll be trying to solve this issue.

**Closed** 2021-02-28 20:34 UTC
Labels: Priority: High, bug, codeheat
