### ISSUE TITLE
Speaker Tab issues on Public Event Pages

### ISSUE THREAD

**Issue by kushthedude** [fossasia/open-event-frontend#3075] opened 2019-06-06 03:05 UTC
**Describe the bug**

- There are some issues for `Speaker Tab` on `Public Event Pages` :
    - If there is more than one speaker , Speaker Image of only one speaker loads up until we click the `Speaker Tab` again .
    - When you want to go to `Info Tab` from `Speaker` it throws a error and this exist only for transition from `Speaker to Info Tab`

**Expected behaviour**

Fix them

**Screenshots**

<img width="1440" alt="Screenshot 2019-06-06 at 8 33 28 AM" src="https://user-images.githubusercontent.com/44091822/59004037-f49bb480-8835-11e9-949b-cb6c57811101.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 73.0.4

**Additional context**

 Needs more review

**Comment by kushthedude** [comment] 2019-06-06 03:06
@uds5501 @shreyanshdwivedi Can you please check the reproducibility ?

**Comment by kushthedude** [comment] 2019-06-06 05:31
@CosmicCoder96 @niranjan94 The following sub error of the issue is due the dependancy `Ember-Scroll-To` which uses `jquery` and is creating issue when we try to move from `Speaker To Info/Ticket/Getting Here` , Please tell should I change the package or any other solution you can see ?

**Comment by uds5501** [comment] 2019-06-12 11:17
@kushthedude I did the exact transitions you specified in this Issue and the errors don't seem to be occuring anymore

**Comment by kushthedude** [comment] 2019-06-12 11:19
First one was solved by recent pr by @shreyanshdwivedi , For dependency one - : 
- go to speaker tab , Hold for about 1-2 sec.
- Try to go back to info tab and see error

**Comment by uds5501** [comment] 2019-06-12 11:23
@kushthedude Followed the steps, can't reproduce.
@ritikamotwani @shreyanshdwivedi @mrsaicharan1 Can you please verify?

**Comment by niranjan94** [comment] 2019-06-16 16:00
@uds5501 I can verify that this issue is indeed reproducible on eventyay.com 

---

@kushthedude please see why the element is coming as undefined. Changing package is not a valid solution.

**Comment by kushthedude** [comment] 2019-06-16 16:02
@niranjan94 Thanks for verifying, I will check it .

**Comment by uds5501** [comment] 2019-06-17 15:04
@kushthedude I think I have a lead regarding this.
Once you reach the speakers tab in https://eventyay.com/e/433e7b16, hovering over the info tab gives you this link: `https://eventyay.com/e/433e7b16/speakers#info` . Which means the session is not being captured correctly.

See here :

https://github.com/fossasia/open-event-frontend/blob/7cbf3fedfbf481314975185c9daac410fefa6a8e/app/templates/components/public/side-menu.hbs#L3-L16

**Comment by kushthedude** [comment] 2019-06-23 03:52
@uds5501 Can you please verify it on local if this exists? I think it has been solved after dependancy upgrade PR by @CosmicCoder96

**Comment by uds5501** [comment] 2019-06-23 06:01
@kushthedude yes, it's working fine now. Hence closing the issue.

**Closed by uds5501** 2019-06-23 06:01 UTC
Labels: bug
