### ISSUE TITLE
Unclear symbols on event listings: circle and forward-arrow

### ISSUE THREAD

**Issue by rolandturner** [fossasia/open-event-frontend#6803] opened 2021-02-23 04:15 UTC
Steps to reproduce the behaviour:
1. Go to https://eventyay.com/e/fa96ae2c/schedule?search=roland
2. Wonder what circle and forward-arrow icons near the top right do
2. Click on circle. Nothing happens apart from a tick appearing.
3. Click on forward arrow. No forwarding action is initiated.

**Expected behaviour**
The circle should instead be a button labelled "Add to My Schedule" (or "Remove from My Schedule"). This helps the user understand what it is, and uses the same name as is used at the top of the page to get to the resulting schedule.

The arrow is universally understood to be "forward this message" which makes no sense in this context. The intended function is that it is a link to the particular event (rather than to the full schedule or search results), which is a very common function, so it should use the very common icon for this function: two or three links of a chain, as used e.g. in filing a GitHub issue) 

**Screenshots**
![Circle and Arrow](https://user-images.githubusercontent.com/646827/108801384-8af6a780-75d0-11eb-8c49-7f4afc851cbf.png)

**Desktop:**
 - OS: Linux
 - Browser: Firefox
 - Version: 85.0

**Comment by mariobehling** [comment] 2021-02-23 09:37
Thanks.

Please change as follows:
1. For the circle on scroll over show a tool tip "Add to My Schedule" or if it is added already "Remove from My Schedule"
2. For the link icon. @rolandturner The right arrow is also often used as a link icon among two other regularly used icons. A question is what is the best icon to symbolize an internal link with more information. We were using the chain link icon elsewhere with the meaning "share links". So, we should differentiate an internal link icon compared to the chain link icon. Image search gives me the following "internal link" icon. Is there anything similar in our icon library?
![internal-icon-21](https://user-images.githubusercontent.com/1583873/108825057-d30ecd80-75c2-11eb-9cf5-856d08f3e120.jpg)

Regarding the circle icon in general, we are following the same approach of sched. However our positioning is different and might need to be change, but this could also mean more design changes in the specific implementation and needs time to test it. So for now the quickest improvements would be here to have a tool tip, I think.

![Screenshot from 2021-02-23 10-27-24](https://user-images.githubusercontent.com/1583873/108824471-0b61dc00-75c2-11eb-9fb4-4c0b22752071.png)

**Comment by ameybhavsar24** [comment] 2021-02-23 10:21
Hi @mariobehling. Can you please assign it to me?

**Comment by ameybhavsar24** [comment] 2021-02-23 11:02
> We don't assign issues to external contributors. Please comment that you're working on the issue after checking that no one else is, and then send a pull request for it. Thank You!

Okay. I'm working on this issue.

**Comment by rolandturner** [comment] 2021-02-23 13:34
> The right arrow is also often used as a link icon among two other regularly used icons

I don't ever recall seeing this. The arrow currently in use is one that I can only ever recall seeing used to mean "forward this".

I'd suggest that there's little value in assigning a special symbol for an internal link. I take the point on chain also being used for share (although 3 boxes joined with 2 lines is perhaps more typical for that?). Another option for a link is the "arrow out of a square" that Wikipedia uses. I'd suggest that this was a better option than inventing a new symbol.

An entirely different option is not to have an icon, just make the title an internal link.

The social media option of using the article time as the permalink isn't available.

Still another option is simply (link) or (permalink). Granted these crowd it a bit.

**Comment by iamdevvalecha** [comment] 2021-05-06 16:25
UNABLE TO REPRODUCE THIS ISSUE.

**Comment by iamdevvalecha** [comment] 2021-05-06 18:27
unable to reproduce this issue.

**Comment by iamdevvalecha** [comment] 2021-05-19 05:36
on it.

**Comment by iamdevvalecha** [comment] 2021-05-19 07:41
![Screenshot from 2021-05-19 13-08-12](https://user-images.githubusercontent.com/71969867/118774651-b1f90880-b8a3-11eb-8fc5-7ced7b3ae907.png)
![Screenshot from 2021-05-19 13-08-49](https://user-images.githubusercontent.com/71969867/118774660-b4f3f900-b8a3-11eb-8954-317d549da1ff.png)
![Screenshot from 2021-05-19 13-09-31](https://user-images.githubusercontent.com/71969867/118774679-b8878000-b8a3-11eb-98ac-8537c390aeac.png)

**Comment by iamdevvalecha** [comment] 2021-05-19 07:44
@rolandturner instead of share link icon we can also have more details button or either we can use angle-down icon which creates 
more sense.

**Comment by rolandturner** [comment] 2021-05-24 04:12
@iamdevvalecha I'm not in a position to make decisions about visual style, I'm merely requesting a feature enhancement.

I suspect that the actual problem here is the lack of a visual style design and therefore decisions that are being made to reduce changes, rather than being user-centric. In particular:
- The [share icon](https://en.wikipedia.org/wiki/Share_icon) is more-or-less universal ([Google's is similar](https://fonts.google.com/icons?selected=Material+Icons&icon.query=share). Apple appears to be suffering not-invented-here syndrome and should be ignored.)  If we're using anything else for this purpose — particularly something that is widely used as a link icon — then the solution would appear to be to stop doing that.
- Links are typically represented as 1, 2, or 3 chain links. We should do the same.
- There is no obvious reason to distinguish between internal and external links, but if we really want then I'd suggest that it's external links which need special treatment and that Wikipedia's approach (arrow pointing out of a box and to the up-right) seems like a good one.

**Closed** 2021-07-26 13:48 UTC
Labels: codeheat, enhancement
