### ISSUE TITLE
Search page not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#691] opened 2017-08-13 14:21 UTC
Search page is not working yet and does not show search options.

Previous implementation of search page is not there.

![screenshot from 2017-08-13 16-20-05](https://user-images.githubusercontent.com/1583873/29250490-646d0eb4-8043-11e7-8329-f9655c0ecbfb.png)

**Comment by niranjan94** [comment] 2017-08-15 03:55
Duplicate of https://github.com/fossasia/open-event-frontend/issues/666

**Closed by niranjan94** 2017-08-15 03:55 UTC
Labels: bug, Priority: Urgent
