### ISSUE TITLE
Registration Page Hangs browser up for 2-3 seconds

### ISSUE THREAD

**Issue by codedsun** [fossasia/open-event-frontend#6543] opened 2021-01-30 09:37 UTC
**Describe the bug**
When the user tries to register itself and toggles between Enter Password and Re-Enter Password field the browser hangs for 2-3 second

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Login, New to Site - Create Accounr
2. Enter the email
3. Now toggle between fields - Hangs

Also when I return from another tab to registration field tab, it hangs.

**Expected behaviour**
It should not hang

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Mac Os
 - Browser [e.g. chrome, safari] - Safari 14.01

**Additional context**

https://user-images.githubusercontent.com/20026440/106352823-1b143a80-630c-11eb-99e3-ca1e4f6ab3ee.mov

**Comment by iamareebjamal** [comment] 2021-01-30 19:13
Please check on production. localhost dev site uses ember debug mode which is excruciatingly slow. Thus, this is only an issue if this happens on production as well.

Which I checked and it didn't happen. Let me know if you reproduce it on prod, I'll reopen

**Comment by codedsun** [comment] 2021-01-31 08:29
@iamareebjamal - This happens on production as well

**Comment by leoshrey** [comment] 2021-01-31 18:32
Hi @codedsun, Are you sure that it isn't any freezing issue with your version of browser? 
Because I am not facing this issue on either sides. 
Please try fixing this issue by:

- Going to Safari -> Preferences -> Autofill
and uncheck all checkboxes. 
- If issue still persists, then try updating your browser with latest version.
- If you are facing this issue again then, try clearing your browser cookies and website data.

And see if this issue still persists.

Update: Seems like it is a common issue by safari users. https://forums.macrumors.com/threads/safari-freeze-on-textbox-focus.2199256/

**Comment by mariobehling** [comment] 2021-05-14 14:53
Cannot reproduce it and we will be moving to ReactJS within a reasonable timeframe. Therefore I think this is out of scope for the current dev plan and I am closing it.

**Closed by mariobehling** 2021-05-14 14:53 UTC
Labels: bug, codeheat

**Comment by Anmollenka** [comment] 2021-05-14 14:55
@mariobehling  Should we not solve issues related to this repo as we are moving to ReactJS?

**Comment by MeghalBisht** [comment] 2021-05-14 15:15
> Should we not solve issues related to this repo as we are moving to ReactJS?

You can look at the opened issues. We will maintain ember site for a good amount of time.
