### ISSUE TITLE
Inconsistent time in scheduler.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossasia/open-event-frontend#2288] opened 2019-03-11 11:45 UTC
**Describe the bug**

Inconsistency in time shown in scheduler.
The time of session to be scheduled shows the time in 12 hrs format (without AM or PM) while the time for schedule is listed in 24 hrs format.

**To Reproduce**
1. Go to `events/<event_num>/scheduler`
2. Add a session to scheduler.
3. See error

**Expected behavior**

Both times should be consistent in terms of format used.
**Screenshots**

![Screenshot from 2019-03-11 17-11-26](https://user-images.githubusercontent.com/21174572/54121729-3aa4d000-4421-11e9-8b9f-de2ae1147f52.png)

**Additional context**

I am working on it.

**Comment by Anupam-dagar** [comment] 2019-03-11 11:46
@CosmicCoder96 I wasn't able to publish the schedule also, the following error was shown as a notification
`Error: Error: Ember Data Request PATCH http://127.0.0.1:5000/v1/events/92063d3b returned a 404 Payload (Empty Content-Type) [object Object]`

**Comment by uds5501** [comment] 2019-03-22 17:19
@Anupam-dagar I can perfectly Publish and Unpublish the schedule without any error
and as for the time inconsistency, I think it's more of a `full-calendar's` discrepancy which can't be solve with our hooks.

Notice the pointed discrepancy in their official documented examples too. 
![image](https://user-images.githubusercontent.com/21087061/54841136-9fe7a380-4cf4-11e9-87cd-d6cfadc738e1.png)

@CosmicCoder96 How should we proceed in this case?

**Comment by CosmicCoder96** [comment] 2019-06-10 16:41
Duplicate of #2560

**Closed by CosmicCoder96** 2019-06-10 16:41 UTC
Labels: bug, dependencies
