### ISSUE TITLE
Implement a Tab "Team" and move Functionality of Team Section in Event Dashboard here

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2960] opened 2019-05-19 15:43 UTC
The team dashboard has an invite and overview feature section. Please improve the team feature as follows:

1. Change the dashboard to only show the information, but without providing functionality. Instead provide a link to the "Team Tab" to edit this.

2. Move the functionality to the "Team Tab" after the "Speakers Tab"

![Screenshot from 2019-05-19 17-36-50](https://user-images.githubusercontent.com/1583873/57984544-0c64f180-7a5d-11e9-9c64-5660e5ee4dae.png)

3. Add two sub tabs similar to the tickets page.

![Screenshot from 2020-08-31 05-32-47](https://user-images.githubusercontent.com/1583873/91680441-85e9fb80-eb4b-11ea-9b00-d2997618fd88.png)

  a) A sub tab "Team" - provide a list of team members here
![Screenshot from 2019-05-19 17-41-49](https://user-images.githubusercontent.com/1583873/57984596-9319ce80-7a5d-11e9-85af-22b178b04e45.png)

  b) A sub tab "Permissions" - provide a table with roles and permissions here. In the first step there is no need to make this editable by the organizer. [Use this Google doc](https://docs.google.com/spreadsheets/d/1iyhvojqrt24969rWu8DB8hlFMQoCU_c9HkGa99zA3_4/edit#gid=0) to get started with the overview. In the first step only implement this for the two main roles - owner and organizer. Other roles can come later. They are marked in gray below.

![Screenshot from 2020-08-31 05-23-28](https://user-images.githubusercontent.com/1583873/91679992-250df380-eb4a-11ea-93b8-46c32f955b39.png)

Also compare to Paper call

![Screenshot from 2019-05-19 17-42-35](https://user-images.githubusercontent.com/1583873/57984599-9a40dc80-7a5d-11e9-9907-43a61587a577.png)

**Comment by uds5501** [comment] 2019-05-19 19:46
@mariobehling Once done with the step 1 of order form addition, i can take this up!

**Comment by CosmicCoder96** [comment] 2019-05-20 08:55
@uds5501 I am breaking this up into sub-issues, will be working on some of them, you can take the rest.

**Comment by amanprateek123** [comment] 2020-09-05 08:00
@mariobehling  If the issue is not assigned to anyone yet,then please assign this issue to me.I want to contribute in open source. And, since I am new to this repo, please guide me through

**Closed** 2020-09-09 18:46 UTC
Labels: feature, parent issue
