### ISSUE TITLE
jpeg format is not supported for speaker image

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-frontend#3434] opened 2019-08-17 13:38 UTC

**Comment by DaKeiser** [comment] 2019-10-26 20:02
Hey @liveHarshit can you tell me the steps to reproduce. I think it seems to be working.

**Comment by liveHarshit** [comment] 2019-10-27 07:03
> Hey @liveHarshit can you tell me the steps to reproduce. I think it seems to be working.

Try to add a speaker in your event with a jpeg format image.

**Comment by DaKeiser** [comment] 2019-10-27 10:18
@liveHarshit I don't think I'm facing that issue. I have replaced a jpeg with a jpeg

![issue](https://user-images.githubusercontent.com/42712983/67633054-1541d500-f8d1-11e9-9172-ef660f2ea06d.gif)

**Comment by snitin315** [comment] 2020-01-25 12:22
I think this one is fixed in #3770

**Comment by kushthedude** [comment] 2020-01-25 22:23
Fixed in #3770

**Closed by kushthedude** 2020-01-25 22:23 UTC
Labels: bug, codeheat
