### ISSUE TITLE
Make side panel in sessions and speakers page sticky

### ISSUE THREAD

**Issue by iamareebjamal** [fossasia/open-event-frontend#4066] opened 2020-02-12 11:35 UTC
After 2-3 scrolls, the side panel drops to the bottom of the page and becomes invisible 

Use `position:sticky` - https://css-tricks.com/position-sticky-2/

**Comment by kushthedude** [comment] 2020-02-13 01:22
Duplicate of #3510

**Comment by iamareebjamal** [comment] 2020-02-13 06:34
Let that issue be about the image sizes

**Closed** 2020-02-13 06:36 UTC
Labels: bug
