### ISSUE TITLE
Organizer Session Page: Filter Option disappeared

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3781] opened 2020-01-09 11:10 UTC
It was possible to filter sessions, e.g. according to track. This option disappeared now.

![Screenshot from 2020-01-09 16-39-55](https://user-images.githubusercontent.com/1583873/72062949-c962d180-32fe-11ea-8f7a-18149ac1f7a4.png)

**Comment by kushthedude** [comment] 2020-01-09 12:29
Duplicate of https://github.com/fossasia/open-event-server/issues/6717

**Closed by kushthedude** 2020-01-09 12:29 UTC
Labels: Priority: High, bug
