### ISSUE TITLE
Page design of event page distorted depending on screen resolution

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4001] opened 2020-02-04 14:14 UTC
Changing the screen resolution distorts the public event page and results in different image ratios and displaced text.

Compare the same page in different resolutions as below.

Desired image ratio is 1:1.

![Screenshot from 2020-02-04 15-12-30](https://user-images.githubusercontent.com/1583873/73752286-f4efa500-4760-11ea-9ca4-b260f87c9eee.png)
![Screenshot from 2020-02-04 15-12-02](https://user-images.githubusercontent.com/1583873/73752287-f5883b80-4760-11ea-81e5-1bf0195dddaf.png)

**Comment by Chaitanyassr** [comment] 2020-02-09 13:28
on it.

**Comment by adrijshikhar** [comment] 2020-02-15 18:32
@Chaitanyassr are you still working on this? i would like to work on this.

**Comment by snitin315** [comment] 2020-02-15 18:33
There is no sign of work done, you can go ahead with this.

**Comment by adrijshikhar** [comment] 2020-02-15 18:34
ok

**Comment by adrijshikhar** [comment] 2020-02-15 18:35
what is the desired image ratio on every screen?

**Comment by adrijshikhar** [comment] 2020-02-16 18:48
@mariobehling can you tell me desired image ratio?

**Comment by snitin315** [comment] 2020-02-16 18:56
@adrijshikhar Refer [#3819 ](https://github.com/fossasia/open-event-frontend/pull/3819)

**Comment by adrijshikhar** [comment] 2020-02-16 19:08
ok

**Comment by adrijshikhar** [comment] 2020-02-16 19:23
how can I reproduce the bug?
should i add an event and then the speakers?

**Comment by snitin315** [comment] 2020-02-16 19:23
Yes

**Comment by adrijshikhar** [comment] 2020-02-16 19:24
ok

**Comment by adrijshikhar** [comment] 2020-02-16 19:38
i am unable to add an event. i entered all the fields and yet the publish button was disabled, and it was showing email unverified even when i have verified my email.
![Screenshot_20200217_010450](https://user-images.githubusercontent.com/41939219/74611454-ff774a80-5121-11ea-8260-06403164b5af.png)

**Comment by iamareebjamal** [comment] 2020-02-16 19:40
How do you know you have verified email?

**Comment by adrijshikhar** [comment] 2020-02-16 19:44
is there any other way to have my email verified?

**Comment by snitin315** [comment] 2020-02-16 19:46
What do you mean by other way? He asked a simple question , the ans should be straight and simple as well.

**Comment by adrijshikhar** [comment] 2020-02-16 19:51
i am did not verify.

**Comment by iamareebjamal** [comment] 2020-02-16 19:52
When you edit your comment after someone else commented, you should mention the edit explicitly

First you said - `even when i have verified my email` and now you edited to `clicked on verify my email and no email was sent.`

**Comment by adrijshikhar** [comment] 2020-02-16 19:54
ok i will keep that in mind.

how can i have my email verified?

**Comment by snitin315** [comment] 2020-02-16 19:57
Are you sure you haven't received any mail.? Have you checked the spam folder ?

**Comment by adrijshikhar** [comment] 2020-02-16 19:59
yes i checked the spam folder and all mail folder, but i haven't received the mail.

**Comment by snitin315** [comment] 2020-02-16 20:03
@iamareebjamal  I tried with reset password , and I didn't received any mail as well.

**Comment by iamareebjamal** [comment] 2020-02-16 20:04
Yes, diagnosing the issue

**Comment by snitin315** [comment] 2020-02-16 20:07
Working fine in production.

**Comment by iamareebjamal** [comment] 2020-02-16 20:14
Culprit - https://github.com/fossasia/open-event-server/issues/6845

**Comment by iamareebjamal** [comment] 2020-02-16 20:19
Should've received the email now

**Comment by snitin315** [comment] 2020-02-16 20:22
Received

![Screenshot_2020-02-17-01-50-13-947_com google android gm](https://user-images.githubusercontent.com/46647141/74612077-0c973800-5128-11ea-8c63-fbe97e5dd044.jpg)

**Comment by adrijshikhar** [comment] 2020-02-16 20:27
it says post request failed when I click on publish event


![Screenshot_20200217_015457asd](https://user-images.githubusercontent.com/41939219/74612162-e1611880-5128-11ea-81ae-520f1d1c4f66.png)

**Comment by iamareebjamal** [comment] 2020-02-16 20:43
Need the error response

**Comment by adrijshikhar** [comment] 2020-02-17 11:23
i tried it again and it worked. Thanks

**Comment by adrijshikhar** [comment] 2020-02-18 08:02
when I add a speaker it throws an error that something went wrong.
i checked the network tab, it says `status code : 422 UNPROCESSABLE ENTITY`.
i only entered the required fields.
i will try with all entries.

**Comment by adrijshikhar** [comment] 2020-02-18 08:04
with all entries it worked. thanks

**Comment by amanprateek123** [comment] 2020-09-05 07:57
If the issue is not assigned to anyone yet,then please assign this issue to me.I want to contribute in open source. And, since I am new to this repo, please guide me through

**Comment by JainJai2305** [comment] 2020-10-30 07:51
Hi, allow me to work on this issue, also is it necessary to participate in code heat first, or anyone can contribute ...

**Comment by snitin315** [comment] 2020-10-30 07:53
Go ahead. Anyone can contribute.

**Closed** 2020-11-18 17:28 UTC
Labels: Priority: High, bug, project
