### ISSUE TITLE
Footer: Sitemap Link not working

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#1820] opened 2019-01-14 22:07 UTC
There is no sitemap link and sitemap.

![screenshot from 2019-01-14 23-06-57](https://user-images.githubusercontent.com/1583873/51144376-2beed200-1851-11e9-8ec2-e428aaf18e14.png)

**Comment by rajvaibhavdubey** [comment] 2019-01-15 17:33
@mariobehling I'm claiming this.

**Comment by CosmicCoder96** [comment] 2019-01-19 06:59
duplicate of #152

**Closed by CosmicCoder96** 2019-01-19 06:59 UTC
Labels: bug
