### ISSUE TITLE
Donation tickets price section's entries are not visible in mobile

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/open-event-frontend#3580] opened 2019-10-29 12:06 UTC
**Describe the bug**
Donation tickets price section's entries are not visible .
Steps to reproduce the behaviour:
1. Go to 'https://eventyay.com/e/ab2d63fe'
2. Go to Donation ticket's price section
3. See error , value in the entry is not visible

**Expected behaviour**
Entry should be visible to user
**Screenshots**
![Screenshot from 2019-10-29 13-18-02](https://user-images.githubusercontent.com/56407566/67765585-8240a080-fa72-11e9-9575-d29c86f55c02.png)

**Additional context**
I am working on this , if you think it is reasonable .

**Comment by kushthedude** [comment] 2019-10-30 06:19
Duplicate of #3511

**Closed by kushthedude** 2019-10-30 06:19 UTC

**Comment by maze-runnar** [comment] 2019-10-30 06:40
This is not diplicate @kushthedude #3511 state the responsiveness while i state only about donation ticket price section not responsive ness. #3511 screen shot not even include the donation ticket section.

**Comment by kushthedude** [comment] 2019-10-30 06:50
> This is not diplicate @kushthedude sir as #3511 state the responsiveness while i state only about donation ticket price section's input box . #3511 screenshot not even include the donation ticket section.

It will be fixed with #3511 since both the issue are related to responsiveness, one is for table and other for the field. Hence, there is no need to open a seperate issue for both.
You may make a PR for #3511 as no one is working on it 😄

**Comment by maze-runnar** [comment] 2019-10-30 08:04
thank you @kushthedude  sir

**Comment by maze-runnar** [comment] 2019-10-30 08:58
Do i need to claim the issue at #3511 ?

**Comment by kushthedude** [comment] 2019-10-30 08:59
Just drop a comment at #3511 , I dont think anyone's working on it lately

**Comment by maze-runnar** [comment] 2019-10-30 09:02
ok :slightly_smiling_face:
