### ISSUE TITLE
User verification: User did not receive a verification email

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#8313] opened 2022-01-26 06:43 UTC
It looks like the system did not send a verification email to a user who signed up with email address that content a dot "." e.g. xx.xxxx@gmail.com. The user then used another email, then she received a verification email 

When I tried to resend a verification email from the admin panel, an error appeared. The error applied for all unverified emails. There are a lot of unverified user the last few weeks. Admin function to resend a verification email does not work.

**Comment by progmatic-99** [comment] 2022-01-27 08:57
Not able to reproduce the error in the admin panel.

**Comment by mariobehling** [comment] 2022-02-01 18:31
Seems to work fine at the moment. Therefore closing it.

**Closed by mariobehling** 2022-02-01 18:31 UTC
Labels: bug
