### ISSUE TITLE
Order  Success Page shows 0 Tickets in Overview

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5667] opened 2020-11-17 09:04 UTC
Some ticket order pages show 0 tickets, but ticket download and invoice work.

Compare: https://eventyay.com/orders/2522eba2-9af2-4315-9a7f-d49da114491d/view

![Screenshot from 2020-11-17 10-04-07](https://user-images.githubusercontent.com/1583873/99369062-40241000-28bc-11eb-9c4a-90bfe44022f7.png)

**Comment by iamareebjamal** [comment] 2020-11-17 09:07
![image](https://user-images.githubusercontent.com/3874064/99369437-6f4d7800-28e2-11eb-9b59-93d0547f7c6d.png)

Duplicate of #4613

**Comment by mariobehling** [comment] 2020-11-17 09:10
The error seems to appear since this merge https://github.com/fossasia/open-event-frontend/pull/5591

**Comment by mariobehling** [comment] 2020-11-17 09:11
Please also check https://eventyay.com/events/1f720482/tickets/orders/completed

**Comment by mariobehling** [comment] 2020-11-17 09:12
The pre-selected field on the order form also appears like an inactive field in the drop-down menu.

![Screenshot from 2020-11-17 10-11-33](https://user-images.githubusercontent.com/1583873/99369948-5aaab900-28bd-11eb-883f-ee218d6b8c16.png)

**Comment by mariobehling** [comment] 2020-11-17 09:13
> Please also check https://eventyay.com/events/1f720482/tickets/orders/completed

0 tickets ordered.

![Screenshot from 2020-11-17 10-13-07](https://user-images.githubusercontent.com/1583873/99370086-8463e000-28bd-11eb-8ae1-5f93b4f37a63.png)

**Comment by iamareebjamal** [comment] 2020-11-17 09:14
No that is the same error as #4613 and existed before merging of #5591 

#5591 doesn't touch any order related file

**Comment by mariobehling** [comment] 2020-11-17 09:15
ok, so first time happened on Nov. 14 it seems.

**Comment by iamareebjamal** [comment] 2020-11-17 09:16
![image](https://user-images.githubusercontent.com/3874064/99370307-880a5d80-28e3-11eb-83f7-9e6df4cbc793.png)

Same as #4613, only happens when you go back and forth the table and detail view

**Comment by mariobehling** [comment] 2020-11-17 09:17
Ok, this bug appears on several different pages now. Quite bad.

**Comment by iamareebjamal** [comment] 2020-11-17 09:18
#4613 and #5176 are same family of issues but this issue is same as #4613 because both issues mention order page and 0 tickets bought.

**Comment by maze-runnar** [comment] 2020-11-18 09:00
is this happening because of `ember-data-has-many-query` as @iamareebjamal once told me in an issue?

**Comment by iamareebjamal** [comment] 2020-11-18 09:01
Yes, the one I linked above

**Comment by maze-runnar** [comment] 2020-11-18 12:38
> Ok, this bug appears on several different pages now. Quite bad.

If it is that bad then Until `ember-data-has-many-query` alternative is not found, for resolving this issue opening page in a new tab for the order is a good workaround, only for opening order details on a new page.

**Comment by iamareebjamal** [comment] 2020-11-18 13:02
That won't fix other issues related to it. We need to create our version of query method

**Comment by maze-runnar** [comment] 2020-11-18 13:03
ok

**Comment by maze-runnar** [comment] 2020-11-18 15:29
https://github.com/emberjs/ember.js/issues/15256
```
items: Ember.computed(function () {
  return this.store.peekAll(modelItemNames);
},
```

`itemsCategoryA: Ember.computed.filterBy('items', 'category', 'a'),`

is it can be a way here?

**Comment by iamareebjamal** [comment] 2020-11-18 16:27
No, we need a way to be able to query related items with custom query parameters

**Closed** 2021-02-17 09:27 UTC
Labels: Priority: High, bug, codeheat
