### ISSUE TITLE
Unable to add order as co-organiser

### ISSUE THREAD

**Issue by cweitat** [fossasia/open-event-frontend#3695] opened 2019-12-11 05:00 UTC
**Describe the bug**
"Oops something went wrong. Please try again" error message appears when I try to add an free order.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the event backend > Tickets
2. Select Quantity '1' and click on 'Add Order'
3. Add 1 free ticket
4. "Oops something went wrong. Please try again" appear. 

Donate works.

**Expected behaviour**
Everything should work. 

**Screenshots**

![image](https://user-images.githubusercontent.com/11439477/70592886-242cde80-1c16-11ea-8154-bf2cc91fb8bd.png)

**Desktop (please complete the following information):**
Chrome, Windows

**Comment by iamareebjamal** [comment] 2019-12-11 05:37
Duplicate of #3696

**Closed by iamareebjamal** 2019-12-11 05:37 UTC

**Comment by cweitat** [comment] 2019-12-11 07:05
How is this a duplicate?

**Comment by iamareebjamal** [comment] 2019-12-11 07:40
Both use same endpoint
