### ISSUE TITLE
stripe setup raising errors

### ISSUE THREAD

**Issue by shreyanshdwivedi** [fossasia/open-event-frontend#3010] opened 2019-05-25 18:06 UTC
**Describe the bug**

After recent dependency update, I disconnected my stripe connection from one if the events and tried to reconnect it.
It is raising this error on FE -
```
Attempted to handle eventdidSetPropertyon <stripe-authorization:1> while in state root.empty. Called with { name: "stripeAuthCode", isDirty: true }.. Please try again
```
And on network response tab this is the error -
```
{"errors": [{"status": 404, "source": {"pointer": ""}, "title": "Object not found", "detail": "Object Not Found"}], "jsonapi": {"version": "1.0"}}
```

**Additional context**

I tried to find out root cause and read somewhere that it is related to dependency.

**Comment by kushthedude** [comment] 2019-05-25 19:34
<img width="999" alt="Screenshot 2019-05-26 at 1 01 53 AM" src="https://user-images.githubusercontent.com/44091822/58373831-15b8f700-7f52-11e9-9f83-476da3445863.png">
Issue with `Connect With Stripe` and Jquery dependancy has been depreciated too

**Comment by niranjan94** [comment] 2019-05-26 07:15
@kushthedude the deprecation warning is _not_ related to this error at all. We can safely ignore the warning as far as the stripe issue is concerned.

**Comment by kushthedude** [comment] 2019-05-26 07:17
@niranjan94 , actually as soon as i click on Connect With Stripe the console flashes this warning and server logs dont show anything, so thought it might be the reason

**Comment by niranjan94** [comment] 2019-05-26 08:04
@shreyanshdwivedi could you tell me when the error occurs ? I tried it on a fresh event (during event creation) and stripe connects properly.

Steps to reproduce would be helpful in solving this.

**Comment by shreyanshdwivedi** [comment] 2019-05-26 08:07
@niranjan94 I disconnected stripe on an already existing event and then tried to reconnect, which caused this error

**Comment by niranjan94** [comment] 2019-05-26 08:27
Lemme try that

**Comment by niranjan94** [comment] 2019-05-26 11:24
@shreyanshdwivedi I'm unable to reproduce this. Could you try again and give a complete stack trace this time (from the console) pointing to the exact line and file the error is being thrown from ?

**Comment by kushthedude** [comment] 2019-05-26 11:25
@niranjan94 , whenever i try to create an event and click connect with
stripe , i get error and nothing happens .

**Comment by niranjan94** [comment] 2019-05-26 11:31
@kushthedude a bit more information about the error would be helpful. all the developers should make it a point to report an error along with a complete stacktrace. Frontend is weird in a way that something that works on one's browser may not always work the same on someone else's. So a stacktrace would be really helpful to nail the bug.

**Comment by kushthedude** [comment] 2019-05-26 11:32
@niranjan94 i provided the console logs above and whenever i try to click
on connect with stripe that depreciation warning comes.

**Comment by niranjan94** [comment] 2019-05-26 11:35
@kushthedude your screenshot contains only the deprecation logs. Which like I said can be ignored. Without any issue _for now_. a deprecation warning is just a _warning_ that something we are using will be removed in the future versions. deprecations by definition will not break anything. 

So, we need to look for errors (red). And also, console logs, paste them as text and not screenshot please. Easier for people to copy paste and use.

**Comment by kushthedude** [comment] 2019-05-26 11:36
Will provide more info .

**Comment by kushthedude** [comment] 2019-05-26 12:39
@niranjan94 Had the same buggy issue on safari which was tweaking with keys , Tried with chrome its working fine and @shreyanshdwivedi I checked adding stripe to a pre-existing event , Its working great too

**Comment by niranjan94** [comment] 2019-05-26 14:50
Thanks for the update @kushthedude 😄 
Closing this issue for now.

**Closed by niranjan94** 2019-05-26 14:50 UTC
