### ISSUE TITLE
Session Editing: Results in 404

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5053] opened 2020-09-11 14:07 UTC
Editing and saving a session as an admin or organizer results in a 404 page.

Expected: 
* Session should be saved
* a message should be shown "Your changes were saved."
* and after saving the user should be redirected to the session page (not the edit session page).

compare: https://eventyay.com/e/8fa7fd14/cfs/session/6258/edit

![Screenshot from 2020-09-11 16-06-49](https://user-images.githubusercontent.com/1583873/92935247-d2d1aa00-f448-11ea-988f-0ef169b22e0a.png)

**Comment by iamareebjamal** [comment] 2020-09-14 14:02
The reason for this is that we transition to 404 if speaker call privacy is set to private. Hence, it is not a bug

**Comment by mariobehling** [comment] 2020-09-14 19:04
I understand, but then we need two different URLs. 

The above URL example is linked from the public speakers page. Then we need to go back to
a) a private session page that the speaker can edit
b) a public session page that is linked from the public speakers page

Compare as anonymous user and click on session https://eventyay.com/e/8fa7fd14/speakers

![Screenshot from 2020-09-14 21-02-44](https://user-images.githubusercontent.com/1583873/93127214-c7db7b80-f6cd-11ea-902d-a6b30a70b7e0.png)

**Comment by mariobehling** [comment] 2020-09-14 19:18
So, I think we are thinking too complicated. Expected is this
1. Edit the page https://eventyay.com/e/8fa7fd14/cfs/session/6258/edit
2. Save the above page.
3. Show the saved page here: https://eventyay.com/e/8fa7fd14/session/6258

Currently when the page is saved it does not redirect to  https://eventyay.com/e/8fa7fd14/session/6258

**Comment by iamareebjamal** [comment] 2020-09-14 21:03
> I understand, but then we need two different URLs.
> 
> The above URL example is linked from the public speakers page. Then we need to go back to
> a) a private session page that the speaker can edit
> b) a public session page that is linked from the public speakers page
> 
> Compare as anonymous user and click on session [eventyay.com/e/8fa7fd14/speakers](https://eventyay.com/e/8fa7fd14/speakers)
> 
> ![Screenshot from 2020-09-14 21-02-44](https://user-images.githubusercontent.com/1583873/93127214-c7db7b80-f6cd-11ea-902d-a6b30a70b7e0.png)

This is another issue and is raised 

> Currently when the page is saved it does not redirect to eventyay.com/e/8fa7fd14/session/6258

OK, will do that

**Comment by iamareebjamal** [comment] 2020-09-14 21:07
But the question remains, should the speaker even be allowed to edit their session or speaker details after CFS is closed or is private? Because eventyay.com/e/8fa7fd14/cfs/session/6258/edit is just for speakers. I'll make it redirect to the individual session/speaker page but the ability to edit these after CFS closing still is questionable

**Comment by mariobehling** [comment] 2020-09-15 02:20
@iamareebjamal We have the "lock" feature for that. The organizer can lock a session and then it should not be editable. If the CfS is closed or not does not matter here.

In regards to the accessibility:
* The page should be accessible to the specific speaker and organizers always.
* It should be accessible to all users (including anonymous users) once the schedule is published.

**Closed** 2020-09-16 06:50 UTC
Labels: Priority: High, Priority: Urgent, bug
