### ISSUE TITLE
Ticket and Invoice Confirmation Email: Formatting Error in Organizer Message in the email

### ISSUE THREAD

**Issue by hpdang** [fossasia/open-event-frontend#6781] opened 2021-02-20 19:38 UTC
**Describe the bug**
After I bought a ticket on https://eventyay.com/e/fa96ae2c, I received two emails with the following titles: 
1. Your tickets for FOSSASIA Summit 2021 (O1613847310-17553)
2. Your order invoice and tickets for FOSSASIA Summit 2021 (O1613847310-17553)

There is an organizer message at the end of both emails. The message has some formatting errors. Please see below: 

![Screenshot from 2021-05-14 17-05-38](https://user-images.githubusercontent.com/1583873/118290337-a047e780-b4d6-11eb-8df2-93be5ffe745e.png)

Below you find a message from the organizer:

Thank you for signing up for the FOSSASIA Summit 2021 on <a href="http://eventyay.com" rel="nofollow" target="_blank">eventyay.com</a>. Our platform enables you to access sessions directly from your browser. On the event days you will see a blue "Join Event" button on the right-hand side. Please click here to open the panel with all video rooms of the event. Additionally there will be schedule and exhibitors pages available with links to the video rooms. We are looking forward to seeing you online at the summit!<br><br>If you are interested to participate in onsite workshops in the Lifelong Learning Institute in Singapore please get an onsite workshops ticket additionally.

**Comment by SwapnilSoni1999** [comment] 2021-03-01 11:40
Probably some parsing issue

**Comment by mariobehling** [comment] 2021-05-14 15:06
This is related to the html code that organizers can enter and which is displayed on the order area. This text should also be converted to html in the emails.

**Comment by sachinchauhan2889** [comment] 2021-05-21 22:16
duplicate of https://github.com/fossasia/open-event-frontend/issues/6983

I have already solved in https://github.com/fossasia/open-event-server/pull/7823 on 12 march.

**Closed by sachinchauhan2889** 2021-05-21 22:16 UTC
Labels: bug, duplicate
