### ISSUE TITLE
Wizard: "Save Draft" and "Publish Button" disappeared

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3186] opened 2019-06-24 16:31 UTC
The buttons "Save Draft" and "Public Button" disappeared when clicking through the wizard. This could be because nothing was changed. However, the buttons should always appear in order to avoid confusion of the user.

Expected:

All steps should have a button:
* Save Draft
* Publish

If the user has not filled in sufficient information to publish an event, there should be a prompt "You need to fill in the ... [info about missing information here] before you can publish your event." Button 1: [Complete Event Info] -> Go to missing info in wizard (eg. step 1), Button 2: [Save Draft] -> Go to Dashboard

![Screenshot from 2019-06-24 18-13-52](https://user-images.githubusercontent.com/1583873/60035893-32119600-96ae-11e9-8689-530b588b3752.png)

**Comment by shreyanshdwivedi** [comment] 2019-06-25 12:09
On it

**Comment by kushthedude** [comment] 2019-06-29 05:58
@shreyanshdwivedi are you able to reproduce this?

**Comment by shreyanshdwivedi** [comment] 2019-06-29 16:28
@kushthedude yes when I don't fill in the location and I jump to last stage by clicking on the `Session and Speakers` heading, the publish button disappeared. Do u want to take over?

**Comment by kushthedude** [comment] 2019-06-29 17:39
#2606 , @shreyanshdwivedi it was because of fact , we have no validation for location field and rather we have implemented an if/else for it , Should I reopen it ?

**Comment by shreyanshdwivedi** [comment] 2019-06-29 17:45
We want something like your PR only. Can you please start discussion on gitter so that others might involve too?

**Comment by uds5501** [comment] 2019-06-30 06:32
@kushthedude The validation on location will force the organiser to  give a location even when there is none ( especially when the user is trying to put up a draft event )

**Comment by prateekj117** [comment] 2019-07-08 18:05
@uds5501 I don't see the harm in making it compulsory to enter location even in case of saving draft as the owner can edit the location later on while publishing.

**Comment by kushthedude** [comment] 2019-07-08 18:17
> @uds5501 I don't see the harm in making it compulsory to enter location even in case of saving draft as the owner can edit the location later on while publishing.

Actually there are online events too , and some events just get the event on air and decide location after the response thats why it should not be compulsory , waiting for @mariobehling response for the location dropdown thing

**Comment by shreyanshdwivedi** [comment] 2019-08-14 17:19
@kushthedude if this issue is solved can you close it

**Comment by kushthedude** [comment] 2019-08-16 21:45
> @kushthedude if this issue is solved can you close it

Nope, A validation is still required, Since with the recent pr made by @uds5501 restricts `saving draft` without location too, I think we are good to add validation and then we can close it there after

**Comment by shreyanshdwivedi** [comment] 2019-08-18 08:32
@uds5501 I think your FE checks handle this. If info is missing while publishing it, it raises an error, right?

**Comment by uds5501** [comment] 2019-08-18 09:06
Yes. It raises an error for that

**Comment by shreyanshdwivedi** [comment] 2019-08-19 23:40
@uds5501 I think then we are good to close this issue, right?

**Comment by shreyanshdwivedi** [comment] 2019-08-20 23:27
> > @kushthedude if this issue is solved can you close it
> 
> Nope, A validation is still required, Since with the recent pr made by @uds5501 restricts `saving draft` without location too, I think we are good to add validation and then we can close it there after

@kushthedude what validation and where? Please elaborate

**Closed** 2019-08-21 19:29 UTC
Labels: Priority: Urgent, bug
