### ISSUE TITLE
show more call for speaker button is visible while there is only one CFS is present 

### ISSUE THREAD

**Issue by maze-runnar** [fossasia/open-event-frontend#3602] opened 2019-11-04 07:35 UTC
**Describe the bug**
show more call for speaker button is visible while there is only one CFS is present 
**Expected behaviour**
the button should be visible when number of call for speaker event is greater than 3

**Screenshots**
![Screenshot from 2019-11-04 12-55-52](https://user-images.githubusercontent.com/56407566/68105162-ad5c4180-ff03-11e9-908a-0603f6ed37ca.png)

**Additional context**
I am working on this, if this is reasonable .

**Comment by kushthedude** [comment] 2019-11-04 15:07
Duplicate of #3309

**Closed by kushthedude** 2019-11-04 15:07 UTC

**Comment by maze-runnar** [comment] 2019-11-05 01:57
I saw that #3309 is opened by you . 
Can i go ahead with that if you say so?

**Comment by kushthedude** [comment] 2019-11-05 01:59
Sure
