### ISSUE TITLE
Implementing the same url dropdown in website textfield of adding speakers

### ISSUE THREAD

**Issue by mohitm15** [fossasia/open-event-frontend#2698] opened 2019-04-16 16:44 UTC
**Is your feature request related to a problem? Please describe.**
 Adding a url dropdown of `https://or http://` in the website text field of add speaker page like implemented in the external link of create event page.

**Describe the solution you'd like**

To implement it to a drop down of urls like in external link section of create event page.

**Screenshot**
current behaviour
![Screenshot 2019-04-16 17:04:31](https://user-images.githubusercontent.com/35539313/56228214-e383c200-6094-11e9-8e74-349b02858e9a.png)

**Additional context**

working on it

**Comment by mohitm15** [comment] 2019-04-16 16:45
@CosmicCoder96 @ritikamotwani reviews required.

**Comment by kushthedude** [comment] 2019-04-16 16:58
@mohitm15 It is duplicate of another issue

**Comment by kushthedude** [comment] 2019-04-16 17:00
Please check the issues before creating a new one #2428

**Closed** 2019-04-16 17:23 UTC
