### ISSUE TITLE
sidebar overflow in event page

### ISSUE THREAD

**Issue by chait04** [fossasia/open-event-frontend#6284] opened 2021-01-09 07:14 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://eventyay.com/e/f4fc71b8'
2. Scroll down to 'Tweets section'

**Screenshots**

![Screenshot (201)_LI](https://user-images.githubusercontent.com/59140343/104085781-0d711500-5278-11eb-8eae-29ff19c220d1.jpg)

**Additional context**

**Comment by chait04** [comment] 2021-01-09 07:15
in ipad view

**Comment by coder34222** [comment] 2021-01-09 07:51
<img width="196" alt="Screen Shot 2021-01-09 at 12 49 32 PM" src="https://user-images.githubusercontent.com/47316899/104086366-2201dd00-5279-11eb-95ef-c22521ca22c8.png">


Are you talking about this issue? overlapping of info icon and @codeheat?

**Comment by chait04** [comment] 2021-01-09 07:59
<strong>The whole tweet 
![Screenshot (204)_LI](https://user-images.githubusercontent.com/59140343/104086515-aacf4780-527e-11eb-8fc7-71d0d60aea74.jpg)
 section  </strong>

**Comment by coder34222** [comment] 2021-01-09 08:00
How can i see it in ipad view on my laptop?

**Comment by MeghalBisht** [comment] 2021-01-09 08:02
Everything works fine for me, please include more information or maybe a relevant screenshot

**Comment by chait04** [comment] 2021-01-09 08:02
press F12 and on top choose device

**Comment by chait04** [comment] 2021-01-09 08:04
> Everything works fine for me, please include more information or maybe a relevant screenshot

This is how it looks in my machine in ipad view

![Screenshot (205)](https://user-images.githubusercontent.com/59140343/104086599-5ed0d280-527f-11eb-8017-8a1b2ba9869e.png)

**Comment by iamareebjamal** [comment] 2021-01-09 08:05
Your issue is unclear. What exactly is the issue?

**Comment by MeghalBisht** [comment] 2021-01-09 08:05
> This is how it looks in my machine in ipad view

This is how it is meant to be I guess

**Comment by coder34222** [comment] 2021-01-09 08:07
I guess the issue is that in ipad view you cannot read the full tweet as you can not scroll horizontally

**Comment by chait04** [comment] 2021-01-09 08:08
<strong> This is laptop view and see the sidebar ( tweet section ) it is clearly visible while in ipad view it is in half </strong>
![Screenshot (207)](https://user-images.githubusercontent.com/59140343/104086658-c6871d80-527f-11eb-8f91-bcc3c108c4a4.png)

**Comment by chait04** [comment] 2021-01-09 08:09
> I guess the issue is that in ipad view you cannot read the full tweet as you can not scroll horizontally

yes .. thats the issue

**Comment by coder34222** [comment] 2021-01-09 08:09
https://user-images.githubusercontent.com/47316899/104086701-e3b9ed00-527b-11eb-89f9-5ed533c6b47a.mov

**Comment by coder34222** [comment] 2021-01-09 08:10
can i work on this issue?

**Comment by Palash1999** [comment] 2021-01-09 08:11
@coder34222 I am new to this community and would also like to help if it is okay with you.

**Comment by MeghalBisht** [comment] 2021-01-09 08:12
Oh okay now I understand, the cropping of tweet continues until mobile view takes over at 767px

**Comment by coder34222** [comment] 2021-01-09 08:17
I followed the docker instructions to run open-event-frontend on my laptop, it is showing me this page when i run it on localhost:4200 , how can i go to eventyay page from here. 


<img width="1440" alt="Screen Shot 2021-01-09 at 1 16 07 PM" src="https://user-images.githubusercontent.com/47316899/104086834-d7825f80-527c-11eb-97e2-03a5e79d8907.png">

**Comment by iamareebjamal** [comment] 2021-01-09 09:06
Docker is for deployment, not development. Please use local installation steps

**Comment by coder34222** [comment] 2021-01-09 12:32
@iamareebjamal, i installed it again using local installation steps, and run it using 'yarn start' but still i am getting the same page. Do i have to navigate to reach the page of 'eventyay'?

**Comment by MeghalBisht** [comment] 2021-01-09 13:22
@coder34222  Try to change the API_HOST to https://api.eventyay.com in .env

**Comment by afzal442** [comment] 2021-01-09 14:17
Ahem, I think u all didn't notice about codeheat challenge is what's all about. Find it from [here](codeheat.org). And try to start off with codeheat labelled issues and before that have a basic understanding of Ember js and all if not. Play around the codes, make changes and see the results but don't PR as long as it's not verified. For more details follow the guidelines given. Thanks. Enjoy coding.

**Comment by farhanalws4u** [comment] 2021-01-10 13:18
could anyone please guide me. I am unable to run this project on my localhost. I followed these instructions [https://github.com/fossasia/open-event-frontend/blob/development/docs/installation/local.md](url). finally when I run the command yarn start, after completion of building nothing shows on my localhost:4200 only a blank page.

**Comment by subodhk01** [comment] 2021-02-15 15:33
Can I work on this issue?

**Comment by mariobehling** [comment] 2021-02-28 20:23
Closing this issue as such design questions should be part of a larger issue that tackles the larger design question here.

**Closed by mariobehling** 2021-02-28 20:23 UTC
