### ISSUE TITLE
User redirected to home screen after authentication

### ISSUE THREAD

**Issue by liveHarshit** [fossasia/open-event-frontend#2932] opened 2019-05-17 07:40 UTC
**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Speaker session without login
2. Login
3. All previous pages lost

**Expected behaviour**
User should continue from the last session.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19
 - Browser Chrome

**Comment by ritikamotwani** [comment] 2019-05-17 15:16
Duplicate of : https://github.com/fossasia/open-event-frontend/issues/2396 and https://github.com/fossasia/open-event-frontend/issues/2370

Redirecting to the previous route is yet to be implemented for some routes.

**Closed by ritikamotwani** 2019-05-17 15:16 UTC
