### ISSUE TITLE
Admin cannot delete spam 

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4006] opened 2020-02-05 04:06 UTC
Admin cannot delete spam event, e.g. https://eventyay.com/e/c040ea6d

Gives "unexpected error".

![Screenshot from 2020-02-05 05-04-42](https://user-images.githubusercontent.com/1583873/73809986-4174c800-47d5-11ea-9aa3-37e54b0b195b.png)

**Comment by kushthedude** [comment] 2020-02-05 04:14
Duplicate of #3998

**Closed by kushthedude** 2020-02-05 04:14 UTC
Labels: Priority: High
