### ISSUE TITLE
CfS: Deadline in wizard different to deadline on public event page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6500] opened 2021-01-27 02:33 UTC
At the FOSSASIA Summit the deadline on the wizard shows 11:59 SGT and the deadline on the public CfS page shows the next day 6:59 SGT. I filled in the CfS while in another timezone. Did the system confuse my browser time?

Compare https://eventyay.com/e/fa96ae2c/cfs

![Screenshot from 2021-01-27 03-30-21](https://user-images.githubusercontent.com/1583873/105934310-3d7a2f80-6050-11eb-81ec-a9dec41580b9.png)
![Screenshot from 2021-01-27 03-29-55](https://user-images.githubusercontent.com/1583873/105934312-3e12c600-6050-11eb-8f5f-37d8ab0f8472.png)

**Comment by iamareebjamal** [comment] 2021-01-27 02:35
Yes, it is again the timezone issue

**Comment by sachinchauhan2889** [comment] 2021-01-29 12:15
looking into this.

**Comment by iamareebjamal** [comment] 2021-01-29 19:45
Duplicate of #6259

**Closed** 2021-01-30 01:26 UTC
Labels: Priority: High, Priority: Urgent, bug
