### ISSUE TITLE
Hide option "use ticketing system" to prevent spam and require tickets to make event live

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2482] opened 2019-04-06 12:37 UTC
Please hide the option "use ticketing system" and only show the option with tickets. Only allow to save an event if a ticket has been added.

![Screenshot from 2019-04-06 20-37-42](https://user-images.githubusercontent.com/1583873/55669598-d8b67980-58ab-11e9-9868-59f6e5b44982.png)

Background:

The option "use ticketing system" is a nice feature to add events of external websites. The options has been abused though to add spam events.

Currently we don't have the resources to implement a thought-through approach and configuration to prevent this.

**Comment by mohitm15** [comment] 2019-04-06 13:08
@mariobehling means by default only show the ticketing system and remove the sliding radio button.

**Comment by kushthedude** [comment] 2019-04-06 14:03
@mohitm15 No , It means until the ticketing module is not active by the admin dont let the user publish event and user should use ticketing in his events by default if not than user should just should be able to make draft . 
I would like to work upon it.

**Comment by CosmicCoder96** [comment] 2019-04-09 05:05
@mariobehling It will hardly prevent any spam events from being created. The user can just enter some garbage values -- for free tickets -- doesn't require any significant effort. The event will go live anyway then.

**Comment by CosmicCoder96** [comment] 2019-05-10 08:36
Featured events have been now implemented.

**Comment by mariobehling** [comment] 2019-05-15 09:21
@mohitm15 

> means by default only show the ticketing system and remove the sliding radio button.

Yes, please remove it for now.

@CosmicCoder96 

> It will hardly prevent any spam events from being created. The user can just enter some garbage values -- for free tickets -- doesn't require any significant effort. The event will go live anyway then.

Yes, it will stop spam bot insterest, cause they are not able to add a link and increase their ranking in that field. There might also be an issue with other links, but let's see how this helps.

Also, currently we focus on income. At a later point we can re-evaluate if we want to add this option again, but for now we need to focus on people who use the system for ticketing.

**Comment by kushthedude** [comment] 2019-06-09 11:40
Duplicate of #2920

**Comment by shreyanshdwivedi** [comment] 2019-06-09 14:08
@kushthedude this issue will automatically be closed once my PR related to it will be merged. The issue you mentioned has a few more points.
I'll suggest you to reopen it

**Comment by kushthedude** [comment] 2019-07-12 00:00
@shreyanshdwivedi I can publish the event without ticket information now also, That's why re-opened the issue.

**Comment by shreyanshdwivedi** [comment] 2019-07-12 00:02
@kushthedude you need to handle this on server to raise appropriate errors.

**Comment by kushthedude** [comment] 2019-07-12 00:06
@shreyanshdwivedi Should I transfer it or create a new issue?

**Comment by shreyanshdwivedi** [comment] 2019-07-12 00:12
Creating a subissue will be better

**Closed** 2019-07-14 07:30 UTC
Labels: feature
