### ISSUE TITLE
Footer Pages Not Editable through Admin UI

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5018] opened 2020-09-08 10:32 UTC
There are four footer pages, that were previously accessible and editable through the UI at https://eventyay.com/admin/content/pages. Please provide access and edit options here again.

Pages concerned are:
* Terms and Conditions  
* Contact  
* Refund Policy  
* Privacy

![Screenshot from 2020-09-08 12-32-23](https://user-images.githubusercontent.com/1583873/92465787-5da77000-f1cf-11ea-93d7-069f6b7cd932.png)

**Comment by iamareebjamal** [comment] 2020-09-08 23:20
Duplicate of #4564

**Closed by iamareebjamal** 2020-09-08 23:20 UTC
Labels: Priority: High, Priority: Urgent, bug
