### ISSUE TITLE
Events with Incomplete Date (without tickets) getting published and shown on start page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#4213] opened 2020-03-10 10:46 UTC
Even though events don't have tickets, they still get published by organizers. The publication is actually blocked when the user tries to publish an event from the wizard, but there are somewhere other ways to publish an event even if the data is not sufficient. 

E.g. on the top right of the event page there is a "Publish" button, that seems to work in some cases even if the data is not sufficient to publish an event. There might be other ways as well. I regularly find incomplete events without tickets on the front page.

Compare: Publish/Unpublish button on the top right even for incomplete events
![Screenshot from 2020-03-10 11-45-17](https://user-images.githubusercontent.com/1583873/76305044-b6e82280-62c4-11ea-8b61-da333a5c0109.png)

**Comment by iamareebjamal** [comment] 2020-07-31 14:41
Duplicate of #4525. Opposite actually

**Closed by iamareebjamal** 2020-07-31 14:41 UTC
Labels: Priority: High, bug
