### ISSUE TITLE
Event Dashboard: Attendee Form Missing

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3188] opened 2019-06-24 16:40 UTC
A button to edit the "Attendee Form" is missing in the event box. Please add it.

![Screenshot from 2019-06-24 18-36-41](https://user-images.githubusercontent.com/1583873/60036324-430ed700-96af-11e9-8b6f-525d0c7a3672.png)

**Comment by kushthedude** [comment] 2019-06-24 16:41
Duplicate of #3175

**Comment by uds5501** [comment] 2019-06-25 15:47
Closed in #3191

**Closed by uds5501** 2019-06-25 15:47 UTC
Labels: bug
