### ISSUE TITLE
Virtual Events: Jitsi Video Does Not Appear

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#6209] opened 2021-01-01 19:41 UTC
The Jitsi Video rooms do not appear in a virtual event for me as an admin user who regularly checks it with Chromium. Originally I thought it is just a temporary issue as it worked again, but now it only works if I open an anonymous browser window or use another browser.

Big Blue Button works however.

Maybe we should start to run the technical meetings with our system in order to identify issues that arise for certain browsers, OSes and configurations.

Compare https://eventyay.com/e/a315169f/video/social-room/64
![Screenshot from 2021-01-01 20-33-52](https://user-images.githubusercontent.com/1583873/103445185-7998bb00-4c71-11eb-95c6-186eaa190cb0.png)

**Comment by iamareebjamal** [comment] 2021-01-02 03:54
I get this if I open the link as an anonymous user 
![image](https://user-images.githubusercontent.com/3874064/103450429-51927180-4cdc-11eb-90cb-261cd77a82cc.png)

**Comment by Sachin21393** [comment] 2021-01-02 12:01
plzz assign this bug to me i can solve it

**Comment by takshch** [comment] 2021-01-02 12:15
@mariobehling Now We can upload video on Github. Also we can use this feature for demonstration of "How to generate issue".
Please try to use video for issue demonstration.

**Comment by mariobehling** [comment] 2021-01-03 12:36
> I get this if I open the link as an anonymous user

Not anonymous, as an admin user or organizer.

**Comment by iamareebjamal** [comment] 2021-01-06 14:33
Not able to reproduce

**Comment by mariobehling** [comment] 2021-01-25 22:54
Trying to narrow this issue down: 

It appears to happen when a user on Chromium/Chrome tries to access an event for the second time. The first time it works and requests the user to accept that the browser gets access to mic and camera. When the user tries to access the room again at a later time these requests do not show up even they should show up. When using a Jitsi room that is not under eventyay the requests also show up. 

Is eventyay blocking those requests somewhere possibly? When trying to access on a fresh anonymous browser window it works as expected.

![Screenshot from 2021-01-25 23-48-51](https://user-images.githubusercontent.com/1583873/105776239-83f45f00-5f68-11eb-8d57-41582eace087.png)

**Comment by mariobehling** [comment] 2021-01-25 23:00
The anonymous browser show the usage of the mic in the browser, but the normal browser with the blank Jitsi screen is missing the mic icon. It somehow did not give the permission again for the same service (that it gave before in the first test).

![Screenshot from 2021-01-25 23-58-35](https://user-images.githubusercontent.com/1583873/105776763-768ba480-5f69-11eb-8dfd-2333619a533d.png)
![Screenshot from 2021-01-25 23-57-59](https://user-images.githubusercontent.com/1583873/105776766-77243b00-5f69-11eb-969c-aefee9759767.png)

**Closed** 2021-04-26 16:59 UTC
Labels: Priority: High, bug, codeheat
