### ISSUE TITLE
Modify side bar to hide tabs for missing data

### ISSUE THREAD

**Issue by geekyd** [fossasia/open-event-frontend#650] opened 2017-08-10 00:21 UTC
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-frontend

**Current behavior:**
![screenshot from 2017-08-10 05-49-28](https://user-images.githubusercontent.com/12807846/29149152-c1bde536-7d8f-11e7-9017-1dddfeae13db.png)

**Expected behavior:**
The tabs should be hidden if the data is not present.

**Comment by CosmicCoder96** [comment] 2017-08-10 03:44
@geekyd @sumedh123 Isn't this a duplicate of https://github.com/fossasia/open-event-frontend/issues/589 ?

**Comment by geekyd** [comment] 2017-08-10 04:21
@CosmicCoder96 No, for the above event, sessionspeaker is enabled but there is no speaker data, also the ticket is enabled but there is no ticked data present.

**Comment by sumedh123** [comment] 2017-08-10 07:09
@geekyd Can you elaborate what is needed in this issue? Because if we check by doing:
```
event.speakers
```
or other things like this, we ll end up making request to speakers. I tried to do that in my PR for #589 but niranjan told me to remove that. Please correct me if I am wrong and explain what is required here?

**Comment by geekyd** [comment] 2017-08-10 22:17
We need a better way to handle this one option is to make all requests in the public route only. That way we wont be making duplicate requests.

**Closed** 2018-07-24 14:04 UTC
Labels: enhancement, has-PR
