### ISSUE TITLE
User can see, edit and delete any event on the system on his/her own dashboard

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#710] opened 2017-08-13 19:17 UTC
Any users see other events in his/her own dashboard and can do anything with the event. It is also possible to see sales, emails of speakers and anything. How is this possible?

![screenshot from 2017-08-13 21-15-47](https://user-images.githubusercontent.com/1583873/29252726-bb58d59a-806c-11e7-8756-49c87d1c18e3.png)

**Comment by niranjan94** [comment] 2017-08-15 03:49
@mariobehling this is pending https://github.com/fossasia/open-event-orga-server/issues/4326 from the server. Not a bug. Just pending implementation.

**Comment by geekyd** [comment] 2017-08-19 02:18
Closing this via https://github.com/fossasia/open-event-frontend/pull/733

**Closed by geekyd** 2017-08-19 02:18 UTC
Labels: blocked-by-server, Priority: Urgent
