### ISSUE TITLE
Events Listing not updated according to map area

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2674] opened 2019-04-16 07:32 UTC
On the page https://next.eventyay.com/explore changing the map area does not change the listed events. Expected: Only events oin the map area should be shown.

![Screenshot from 2019-04-16 13-44-25](https://user-images.githubusercontent.com/1583873/56190464-76503c80-6054-11e9-8190-274251fbfdd1.png)

**Comment by kushthedude** [comment] 2019-04-16 08:05
Duplicate of #2171  , PS -: I am working on #2171

**Comment by CosmicCoder96** [comment] 2019-05-28 20:53
Duplicate of #2171

**Closed by CosmicCoder96** 2019-05-28 20:53 UTC
Labels: bug
