### ISSUE TITLE
Add new link button should be disabled (If no input) while adding new links during creation of an event.

### ISSUE THREAD

**Issue by bsanket16** [fossasia/open-event-frontend#4956] opened 2020-09-03 13:22 UTC
**Describe the bug**
While adding links in the Links and social media section, I feel that the add button should be disabled until the input field contains some links/text.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '/create'
2. Click on add (+) button

**Expected behaviour**
Add new link button should be disabled until some link or text is provided.

**Screenshots**
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/66514052/92120132-4efb3a80-ee16-11ea-99f1-6ee680b0ca7e.gif)

**Additional context**
This is my first time here and I would like to start with this issue, any help/suggestion is appreciated.

**Comment by iamareebjamal** [comment] 2020-09-03 13:53
Check which component it is using Ember Inspector extension and read the relevant component's code

**Comment by bsanket16** [comment] 2020-09-03 14:58
I am on it. 👍 @iamareebjamal

**Comment by amanprateek123** [comment] 2020-09-05 07:58
@bsanket16  If the issue is not assigned to anyone yet,then please assign this issue to me.I want to contribute in open source. And, since I am new to this repo, please guide me through

**Closed** 2020-09-08 04:46 UTC
