### ISSUE TITLE
Notifications Panel does not show "Unread Messages"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#2975] opened 2019-05-20 13:19 UTC
Unread messages are not showing up in the Unread Messages page.

![Screenshot from 2019-05-20 15-16-09](https://user-images.githubusercontent.com/1583873/58024508-9cb13e00-7b12-11e9-997c-6b660bc1974c.png)

**Comment by shreyanshdwivedi** [comment] 2019-05-20 13:20
Will work on it.

**Comment by kushthedude** [comment] 2019-05-20 23:45
@shreyanshdwivedi can you reproduce it ?

**Comment by shreyanshdwivedi** [comment] 2019-05-22 20:51
@kushthedude @mariobehling no. I'm also not able to reproduce it. I just ordered a ticket and viewed the notifications in the panel.
![Screenshot_2019-05-23 Unread Notifications Open Event](https://user-images.githubusercontent.com/25428397/58208003-79001a80-7d01-11e9-9421-268e2cc65ee0.png)

**Comment by shreyanshdwivedi** [comment] 2019-05-28 18:29
@CosmicCoder96 @uds5501 @kushthedude  I'm unable to reproduce this issue on my local. Please verify is this issue persists or we can close this issue

**Comment by kushthedude** [comment] 2019-05-28 18:33
@shreyanshdwivedi 
We can verify it on `Eventyay` , Did you get the notification when i acceptance my invite as `Co-Organizer` for your event ? , If you are not sure. , I will create an Proposal and you can check if you get the `Notification` under the panel .

**Comment by shreyanshdwivedi** [comment] 2019-05-29 20:21
@kushthedude I didn't receive a notification when you accepted the invitation. However every time you were accepting/rejecting a proposal, it came to my notification panel. I don't remember if I read it earlier or not but it is showing in my read msgs.

![Screenshot_2019-05-30 All Notifications eventyay](https://user-images.githubusercontent.com/25428397/58588142-a5c1ae00-827c-11e9-9657-d5e13453a4b8.png)

**Comment by shreyanshdwivedi** [comment] 2019-05-30 04:05
@uds5501 @mrsaicharan1 can you please verify if this issue persist or not?

**Comment by kushthedude** [comment] 2019-05-30 07:10
@shreyanshdwivedi Just verified on `eventyay` , Getting `Unread Notification` as expected , @CosmicCoder96 Request you to close the following
<img width="1040" alt="Screenshot 2019-05-30 at 12 39 45 PM" src="https://user-images.githubusercontent.com/44091822/58615189-134ef800-82d8-11e9-94cf-01a59b6644be.png">

**Comment by shreyanshdwivedi** [comment] 2019-06-01 09:51
@CosmicCoder96 please close this issue. It isn't reproducible

**Closed** 2019-06-03 13:09 UTC
Labels: bug
