### ISSUE TITLE
Not showing complete speaker list 

### ISSUE THREAD

**Issue by daretobedifferent18** [fossasia/open-event-frontend#5952] opened 2020-12-07 17:35 UTC
**Describe the bug**

Not showing a complete list of Speakers

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://eventyay.com/e/ae73f280/speakers
2. Click on 'Injee Kim' Speaker
3. Now click on 'Mentor Feedback Hour: Culture, Design and Education Topics'

This bug is removed after reloading the page

Actual | Expected
--------- | ---------
![Screenshot from 2020-12-07 22-45-25](https://user-images.githubusercontent.com/71120226/101382894-7b739680-38de-11eb-9795-387c16193e69.png) | ![Screenshot from 2020-12-07 22-45-45](https://user-images.githubusercontent.com/71120226/101382889-79a9d300-38de-11eb-99d8-0456365bd23a.png)

**Comment by palakshivlani-11** [comment] 2020-12-08 06:47
I would like to take up this issue

**Comment by takshch** [comment] 2020-12-09 11:59
@mariobehling Please assign this issue to me.

**Comment by takshch** [comment] 2020-12-10 08:38
@iamareebjamal Can you please assign this issue to me as no one is assigned to this issue till now.

**Comment by takshch** [comment] 2020-12-10 09:56
I am working on this issue after checking that no one else is working.

**Comment by btapash** [comment] 2020-12-11 07:34
I am working on this issue!

**Comment by takshch** [comment] 2020-12-11 07:36
> I am working on this issue!

I am already working on this issue from yesterday. Please take another issue.

**Comment by btapash** [comment] 2020-12-11 07:39
> > I am working on this issue!
> 
> I am already working on this issue from yesterday. Please take another issue.

Okay!

**Comment by takshch** [comment] 2020-12-11 16:17
I tried to generate or produce the issue but everything goes expected there is nothing which is unexpected.
@mariobehling Please take a look at this issue and close this issue.

**Comment by btapash** [comment] 2020-12-11 16:21
No, it is showing unexpected result. After refreshing the page the result
come as expected.

**Comment by takshch** [comment] 2020-12-12 08:25
@btapash Can you please connect with me. I failed to produce the issue.

**Comment by takshch** [comment] 2020-12-14 21:13
I am not working on this issue as i am unable to produce the same issue. 
If anyone wants to work on this issue, then take this issue and go ahead.
@btapash

**Comment by MohitPatni0731** [comment] 2020-12-16 18:37
can I take this issue

**Comment by FlashV998** [comment] 2020-12-19 14:06
@daretobedifferent18 can't able to reproduce the behaviour, can you please tell whether this bug is resolved or not yet,because on the given link there's no error shown.

**Comment by iamareebjamal** [comment] 2021-01-04 07:17
It is fixed now AFAIK. Reopen if not

**Closed by iamareebjamal** 2021-01-04 07:17 UTC
Labels: bug, codeheat
