### ISSUE TITLE
For Event Registration: Can Not Edit Email 

### ISSUE THREAD

**Issue by Parth910** [fossasia/open-event-frontend#3374] opened 2019-08-11 09:57 UTC
**Describe the bug**
when we register for any event email is compulsory but we can not edit an email

**Expected behaviour**
An email is provided already 
or
we can edit or add email manually

**Screenshots**

![Screenshot from 2019-08-11 15-00-46](https://user-images.githubusercontent.com/31615065/62832465-2113e880-bc4c-11e9-8653-12f43cb6a65e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux
 - Browser: chrome

**Comment by shreyanshdwivedi** [comment] 2019-08-11 09:58
@Parth910 I'll take a look at it if you are not working on this

**Comment by Parth910** [comment] 2019-08-11 09:59
@shreyanshdwivedi I am working on this

**Comment by shreyanshdwivedi** [comment] 2019-08-11 10:00
Okay, so order is associated with an user and if you change the email we'll have to verify the email again to ensure it is not a spam order.
Therefore I think email should not be allowed to be. updated in the order section. You can visit your profile and update it if you want

**Comment by Parth910** [comment] 2019-08-11 10:05
yes but what if my email is not showing in order section, how can I add?

**Comment by kushthedude** [comment] 2019-08-11 10:50
Email is compulsory, and the email in ticket buyer is uneditable unless you are using a guest account for placing order.
Please give exact steps since tue following part was never buggy.

**Comment by kushthedude** [comment] 2019-08-11 12:10
Closing the following, Please give exact steps to reproduce. As the email here should be given during registration and it should be non-editable as is.
Thanks

**Closed by kushthedude** 2019-08-11 12:10 UTC
