### ISSUE TITLE
Page is not scrollable on mobile View as well as phone.

### ISSUE THREAD

**Issue by lopeselio** [fossasia/open-event-frontend#4547] opened 2020-07-11 17:48 UTC
**Describe the bug**
The page cannot be scrolled on mobile view

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://eventyay.com/'
2. Scroll down to see events on mobile view or one phone.
3. Page is not scrollable on phone and also in mobile view in Chrome as well as safari

**Expected behaviour**
The user should be able to scroll down to see more events
![1](https://user-images.githubusercontent.com/43913734/87230262-5d0b7c80-c3cc-11ea-9709-f385b3230f0e.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Linux Mint, Windows]
 - Version [e.g. 83.0.4103.61]

**Smartphone (please complete the following information):**
 - Device: [e.g. OPPO  f11 Pro]
 - OS: [e.g. Android ]
 - Browser [e.g.Chromei]
 - Version [e.g. 79.0.3945.136]

**Additional context**
It would be better if the page is scrollable on mobile view as most users worldwide use phone for connecting, instead of desktops, laptops.

**Comment by iamareebjamal** [comment] 2020-07-11 18:45
Duplicate of #4526 

A fix is in works

**Closed by iamareebjamal** 2020-07-11 18:45 UTC
