### ISSUE TITLE
My Sessions: Displays Sessions twice

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#3504] opened 2019-09-03 00:58 UTC
Accepted sessions are displayed twice on the My Sessions page at https://eventyay.com/my-sessions/upcoming

![Screenshot from 2019-09-03 02-49-17](https://user-images.githubusercontent.com/1583873/64137123-8cd61500-cdf6-11e9-8ec3-31fda321ee20.png)

**Comment by rkpattnaik780** [comment] 2019-09-28 12:57
I would like to work on this issue.

**Comment by kushthedude** [comment] 2019-10-03 22:16
Go ahead

**Comment by rkpattnaik780** [comment] 2019-10-04 10:28
Hey @kushthedude , I am unable to reproduce this bug locally. Creating a session is giving the following error in console : 
![Screenshot from 2019-10-04 15-54-24](https://user-images.githubusercontent.com/23582438/66200857-94236380-e6bf-11e9-824f-f280ef770ab6.png)
And this error message in the response : 
    {"errors": [{"detail": "Not a valid URL.", "source": {"pointer": "/data/attributes/slides-url"}, "status":  "422", "title": "Validation error"}], "jsonapi": {"version": "1.0"}}

**Comment by kushthedude** [comment] 2019-12-15 18:16
Duplicate of #3703

**Closed by kushthedude** 2019-12-15 18:16 UTC
Labels: bug, codeheat
