### ISSUE TITLE
Implement My Tickets tab

### ISSUE THREAD

**Issue by srv-twry** [fossasia/open-event-frontend#1363] opened 2018-07-08 05:07 UTC
**Is your feature request related to a problem? Please describe.**

The required API for this tab in implemented in the server and hence it should be integrated in the FE.

**Comment by srv-twry** [comment] 2018-07-08 06:04
The main card used in the v1.

```
{% macro order_element(order) %}
    <a href="{{ url_for('ticketing.view_order_after_payment', order_identifier=order.identifier) }}">
        <div class="col-xs-12 event-holder">
            <div class="thumbnail row">
                <div class="img-box col-md-3 col-sm-3 col-xs-3">
                    <img class="event-image" style="width:100%" src='
                            {% if order.event.logo %}{{ order.event.logo }}{% elif order.event.background_url %}{{ order.event.thumbnail }}{% elif order.event.sub_topic %}{% set vars = {"foo": False} %}{% for custom_image in custom_placeholder %}{% if custom_image.name == order.event.sub_topic %}{{ custom_image.url }}{% if vars.update({"foo": True}) %} {% endif %}{% endif %}{% endfor %}{% if not vars.foo %}{{ url_for("static", filename="placeholders/" + placeholder_images[order.event.sub_topic]) }}{% endif %}{% elif order.event.topic %}{% set vars = {"foo": False} %}{% for custom_image in custom_placeholder %}{% if custom_image.name == order.event.topic %}{{ custom_image.url }}{% if vars.update({"foo": True}) %} {% endif %}{% endif %}{% endfor %}{% if not vars.foo %}{ url_for("static", filename="placeholders/" + placeholder_images[order.event.topic])}}{% endif %}{% else %}{% set vars = {"foo": False} %}{% for custom_image in custom_placeholder %}{% if custom_image.name == "Other" %}{{ custom_image.url }}{% if vars.update({"foo": True}) %} {% endif %}{% endif %}{% endfor %}{% if not vars.foo %}{{ url_for("static", filename="placeholders/" + placeholder_images["Other"]) }}{% endif %}{% endif %}'
                         onerror="imgError(this, true);">
                </div>
                <div class="caption col-md-9 col-sm-9 col-xs-9">
                    <small class="time">
                        {% if order.event %}
                            {{ order.event.start_time.strftime('%a, %B %d %I:%M %p') }}{% endif %}</small>
                    <h4 class="name">{{ order.event.name }}</h4>
                    <small class="location_name">
                        {% if order.event %}{{ order.event.location_name.split(",")[0] }}{% endif %}</small>
                    <hr>
                    <p class="tags">
                    <span class="filter-hashtag">
                        {% if order.amount == 0 %}Free{% else %} {{ order.event.payment_currency | currency_symbol }} {{ order.amount | money }}{% endif %}
                        order #{{ order.get_invoice_number() }} on {{ order.completed_at.strftime('%B %d, %Y %I:%M %p') }}
                    </span>
                    </p>
                </div>
            </div>
        </div>
    </a>
{% endmacro %}

```

**Comment by CosmicCoder96** [comment] 2018-07-11 11:56
duplicate of #1347

**Closed by CosmicCoder96** 2018-07-11 11:56 UTC
Labels: api-integration, feature
